#!/usr/bin/env python3
"""Build a deterministic test, documentation, profiling, and delta index.

The quality index is intentionally an audit and triage product.  It reports
what can be proven from the source tree, optional coverage profiles, and Git
metadata; it does not turn heuristics into a claim that a repository is 100%
covered.  The output is safe to regenerate for any local folder, including a
folder that is not a Git worktree.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Mapping, Sequence


SCRIPT_VERSION = "1.0.1"
PROJECT = "RKC"
PUBLISHER = "NeuroForgeIO"
LICENSE = "MIT"
DEFAULT_OUTPUT_NAME = ".rkc-quality"

SOURCE_LANGUAGES = {
    ".go": "go",
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".rs": "rust",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".rb": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
}
DOCUMENT_SUFFIXES = {".md", ".mdx", ".rst"}
EXCLUDED_COMPONENTS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "node_modules",
        "vendor",
        "target",
        "build",
        "dist",
        "bin",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".cache",
        ".rkc",
        ".rkc-state",
        ".rkc-coverage",
        ".rkc-models",
        ".rkc-runtime",
        ".rkc-downloads",
        "coverage",
        "htmlcov",
    }
)
GENERATED_MARKERS = (
    "code generated",
    "do not edit",
    "generated by",
)
PROFILE_RE = re.compile(
    r"^(?P<file>.+):\d+\.\d+,\d+\.\d+ (?P<statements>\d+) (?P<count>\d+)$"
)
GO_PACKAGE_COMMENT_RE = re.compile(
    r"(?m)^[ \t]*//[ \t]+Package[ \t]+[A-Za-z_][A-Za-z0-9_]*\b"
)
GO_PACKAGE_DECL_RE = re.compile(
    r"(?m)^[ \t]*package[ \t]+([A-Za-z_][A-Za-z0-9_]*)\b"
)
TEST_SUFFIXES = ("_test", ".test", ".spec")


class QualityIndexError(RuntimeError):
    """Raised when an index cannot be built without guessing."""


def _relative(path: Path, root: Path) -> str:
    try:
        # ``abspath`` normalises lexical ``..`` components without following
        # a symlink.  Symlinks are intentionally reported by ``_walk_files``
        # rather than silently resolving outside the selected root.
        lexical = Path(os.path.abspath(os.fspath(path)))
        return lexical.relative_to(root.resolve()).as_posix()
    except ValueError as exc:
        raise QualityIndexError(f"path escapes repository root: {path}") from exc


def _validate_root(root: Path) -> Path:
    if not root.exists() or root.is_symlink() or not root.is_dir():
        raise QualityIndexError(f"root must be a real directory: {root}")
    return root.resolve()


def _is_excluded(relative: str, output_relative: str | None) -> bool:
    parts = Path(relative).parts
    if any(part in EXCLUDED_COMPONENTS or part.startswith(".rkc-") for part in parts):
        return True
    if output_relative and (
        relative == output_relative or relative.startswith(output_relative + "/")
    ):
        return True
    return False


def _walk_files(root: Path, output: Path | None) -> tuple[list[Path], list[dict[str, str]]]:
    """Return regular files and explicit symlink exclusions in stable order."""
    output_relative: str | None = None
    if output is not None:
        try:
            output_relative = _relative(output, root)
        except QualityIndexError:
            output_relative = None
    files: list[Path] = []
    exclusions: list[dict[str, str]] = []
    for current, directories, names in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        kept_directories: list[str] = []
        for name in sorted(directories):
            candidate = current_path / name
            relative = _relative(candidate, root)
            if _is_excluded(relative, output_relative):
                continue
            try:
                info = os.lstat(candidate)
            except OSError as exc:
                raise QualityIndexError(f"cannot inspect {relative}: {exc}") from exc
            if stat.S_ISLNK(info.st_mode):
                exclusions.append({"path": relative, "reason": "symlink-directory"})
                continue
            if not stat.S_ISDIR(info.st_mode):
                raise QualityIndexError(f"directory entry is not a directory: {relative}")
            kept_directories.append(name)
        directories[:] = kept_directories
        for name in sorted(names):
            candidate = current_path / name
            relative = _relative(candidate, root)
            if _is_excluded(relative, output_relative):
                continue
            try:
                info = os.lstat(candidate)
            except OSError as exc:
                raise QualityIndexError(f"cannot inspect {relative}: {exc}") from exc
            if stat.S_ISLNK(info.st_mode):
                exclusions.append({"path": relative, "reason": "symlink-file"})
            elif stat.S_ISREG(info.st_mode):
                files.append(candidate)
            else:
                exclusions.append({"path": relative, "reason": "non-regular-file"})
    files.sort(key=lambda path: _relative(path, root))
    exclusions.sort(key=lambda item: (item["path"], item["reason"]))
    return files, exclusions


def _file_stats(path: Path, root: Path) -> dict[str, Any]:
    digest = hashlib.sha256()
    size = 0
    lines = 0
    try:
        with path.open("rb") as handle:
            while True:
                chunk = handle.read(1024 * 1024)
                if not chunk:
                    break
                digest.update(chunk)
                size += len(chunk)
                lines += chunk.count(b"\n")
    except OSError as exc:
        raise QualityIndexError(f"cannot read {_relative(path, root)}: {exc}") from exc
    if size and lines == 0:
        lines = 1
    return {
        "path": _relative(path, root),
        "bytes": size,
        "lines": lines,
        "sha256": digest.hexdigest(),
    }


def _text(path: Path, limit: int = 1_048_576) -> str:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            return handle.read(limit)
    except OSError:
        return ""


def _generated(path: Path) -> bool:
    # Generated markers are a source-header convention. Restrict the scan to
    # comment-looking lines near the top so ordinary runtime prose such as
    # ``Generated by RKC ...`` cannot hide a real source file from the audit.
    for line in _text(path, 16_384).splitlines()[:80]:
        stripped = line.strip().lower()
        if not stripped.startswith(("//", "#", "/*", "*", "<!--", ";")):
            continue
        comment = re.sub(r"^(?://|#+|/\*+|\*+|<!--|;)[ \t]*", "", stripped)
        if any(marker in comment for marker in GENERATED_MARKERS):
            return True
    return False


def _normalise_stem(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def _is_test_path(relative: str) -> bool:
    path = Path(relative)
    lowered_parts = {part.lower() for part in path.parts}
    name = path.name.lower()
    return (
        "test" in lowered_parts
        or "tests" in lowered_parts
        or name.startswith("test_")
        or any(name.endswith(suffix + path.suffix) for suffix in TEST_SUFFIXES)
        or any(name.removesuffix(path.suffix).endswith(suffix) for suffix in TEST_SUFFIXES)
    )


def _language(path: Path) -> str | None:
    return SOURCE_LANGUAGES.get(path.suffix.lower())


def _text_mentions_path(text: str, relative: str) -> bool:
    """Return whether a test explicitly names a source path or basename.

    Cross-language harnesses (for example Python tests that execute shell
    workflows) are common in real repositories.  Requiring the source and
    test to have the same language would hide that evidence, so an explicit
    path mention is accepted as a conservative association.  Boundary checks
    avoid matching a short stem embedded in an unrelated identifier.
    """
    lowered = text.lower()
    candidates = [relative.lower()]
    basename = Path(relative).name.lower()
    if len(basename) >= 7:
        candidates.append(basename)
    for candidate in candidates:
        pattern = rf"(?<![a-z0-9_.-]){re.escape(candidate)}(?![a-z0-9_.-])"
        if re.search(pattern, lowered):
            return True
    return False


def _test_evidence(
    relative: str,
    language: str,
    all_source_paths: Sequence[str],
    test_texts: Mapping[str, str] | None = None,
    package_name: str | None = None,
) -> list[str]:
    source_path = Path(relative)
    source_stem = _normalise_stem(source_path.stem)
    candidates: list[str] = []
    for candidate in all_source_paths:
        if not _is_test_path(candidate):
            continue
        test_path = Path(candidate)
        if test_texts and _text_mentions_path(test_texts.get(candidate, ""), relative):
            candidates.append(candidate)
            continue
        if language == "go" and package_name and len(package_name) >= 4:
            selector = rf"(?<![A-Za-z0-9_]){re.escape(package_name)}\s*\."
            if re.search(selector, test_texts.get(candidate, "") if test_texts else ""):
                candidates.append(candidate)
                continue
        if _language(test_path) != language:
            continue
        test_stem = _normalise_stem(test_path.stem)
        for prefix in ("test", "tests"):
            if test_stem.startswith(prefix):
                test_stem = test_stem[len(prefix) :]
        for suffix in TEST_SUFFIXES:
            normal_suffix = _normalise_stem(suffix)
            if test_stem.endswith(normal_suffix):
                test_stem = test_stem[: -len(normal_suffix)]
        same_directory = test_path.parent == source_path.parent
        if language == "go" and same_directory:
            candidates.append(candidate)
        elif test_stem and (test_stem == source_stem or source_stem in test_stem):
            candidates.append(candidate)
    return sorted(set(candidates))[:32]


def _go_package_documentation(
    root: Path, source_paths: Sequence[str]
) -> dict[str, list[str]]:
    """Map Go package directories to source files carrying package docs."""
    evidence: dict[str, list[str]] = {}
    for relative in source_paths:
        path = Path(relative)
        if path.suffix.lower() != ".go" or _is_test_path(relative):
            continue
        candidate = root / relative
        if _generated(candidate):
            continue
        if GO_PACKAGE_COMMENT_RE.search(_text(candidate, 16_384)):
            evidence.setdefault(path.parent.as_posix(), []).append(relative)
    return {directory: sorted(set(paths)) for directory, paths in evidence.items()}


def _go_package_name(path: Path) -> str | None:
    match = GO_PACKAGE_DECL_RE.search(_text(path, 16_384))
    return match.group(1) if match else None


def _documentation_evidence(
    relative: str,
    path: Path,
    documentation: Mapping[str, str],
    root: Path,
    go_package_docs: Mapping[str, Sequence[str]] | None = None,
) -> dict[str, Any]:
    source_text = _text(path, 65_536)
    evidence: list[str] = []
    sibling_doc = path.parent / "doc.go"
    if path.suffix.lower() == ".go" and sibling_doc.is_file() and not sibling_doc.is_symlink():
        evidence.append(_relative(sibling_doc, root))
    if path.suffix.lower() == ".go":
        package_directory = _relative(path.parent, root)
        package_docs = go_package_docs.get(package_directory, ()) if go_package_docs else ()
        if go_package_docs is None:
            for candidate in sorted(path.parent.glob("*.go")):
                if candidate.is_symlink() or not candidate.is_file():
                    continue
                candidate_relative = _relative(candidate, root)
                if _is_test_path(candidate_relative) or _generated(candidate):
                    continue
                if GO_PACKAGE_COMMENT_RE.search(_text(candidate, 16_384)):
                    package_docs = [*package_docs, candidate_relative]
        evidence.extend(package_docs)
    if path.suffix.lower() == ".py":
        try:
            tree = ast.parse(source_text or "\n")
            if ast.get_docstring(tree):
                evidence.append("in-source-docstring")
        except SyntaxError:
            evidence.append("syntax-unavailable")
    basename = path.name.lower()
    exact = relative.lower()
    for doc_path, text in documentation.items():
        if exact in text or (len(basename) >= 7 and basename in text):
            evidence.append(doc_path)
    unique = sorted(set(evidence))
    return {
        "status": "evidence" if unique else "gap",
        "evidence": unique,
        "method": "Go-package-comment/path-or-in-source-docstring",
    }


def _run_git(root: Path, arguments: Sequence[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            ["git", "-C", str(root), *arguments],
            check=False,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise QualityIndexError(f"Git inspection failed: {exc}") from exc


def _git_identity(root: Path) -> dict[str, Any]:
    commit = _run_git(root, ["rev-parse", "--verify", "HEAD"])
    tree = _run_git(root, ["rev-parse", "--verify", "HEAD^{tree}"])
    if commit.returncode != 0 or tree.returncode != 0:
        detail = (commit.stderr or tree.stderr or "not a Git worktree").strip()
        return {"status": "unavailable", "reason": detail[:240]}
    return {
        "status": "available",
        "commit": commit.stdout.strip(),
        "tree": tree.stdout.strip(),
    }


def _parse_git_changes(text: str) -> list[dict[str, str]]:
    tokens = text.split("\0")
    changes: list[dict[str, str]] = []
    index = 0
    while index < len(tokens) and tokens[index]:
        status = tokens[index]
        index += 1
        if status[:1] in {"R", "C"}:
            if index + 1 >= len(tokens) or not tokens[index] or not tokens[index + 1]:
                raise QualityIndexError("Git returned an incomplete rename record")
            changes.append(
                {
                    "status": "renamed" if status[0] == "R" else "copied",
                    "path": tokens[index + 1],
                    "previous_path": tokens[index],
                }
            )
            index += 2
        else:
            if index >= len(tokens) or not tokens[index]:
                raise QualityIndexError("Git returned an incomplete change record")
            changes.append({"status": status, "path": tokens[index]})
            index += 1
    return changes


def _git_changes(root: Path, base: str | None, identity: Mapping[str, Any]) -> dict[str, Any]:
    if identity.get("status") != "available":
        return {"status": "unavailable", "reason": identity.get("reason", "Git unavailable"), "items": []}
    if base:
        arguments = ["diff", "--name-status", "-z", "--find-renames", base, "HEAD", "--"]
        scope = f"{base}..HEAD"
    else:
        arguments = ["diff", "--name-status", "-z", "--find-renames", "HEAD", "--"]
        scope = "working-tree"
    diff = _run_git(root, arguments)
    if diff.returncode != 0:
        return {"status": "unavailable", "reason": (diff.stderr or "git diff failed").strip()[:240], "items": []}
    changes = _parse_git_changes(diff.stdout)
    untracked = _run_git(root, ["ls-files", "--others", "--exclude-standard", "-z"])
    if untracked.returncode == 0:
        changes.extend({"status": "untracked", "path": path} for path in untracked.stdout.split("\0") if path)
    changes.sort(key=lambda item: (item["path"], item.get("previous_path", ""), item["status"]))
    return {"status": "available", "scope": scope, "items": changes}


def _resolve_profile_path(value: str, source_paths: set[str], root: Path) -> str | None:
    normal = value.replace("\\", "/")
    candidate = Path(normal)
    if candidate.is_absolute():
        try:
            normal = _relative(candidate, root)
        except QualityIndexError:
            normal = candidate.as_posix()
    normal = normal.lstrip("./")
    if normal in source_paths:
        return normal
    matches = sorted(path for path in source_paths if normal.endswith("/" + path) or normal == path)
    return matches[0] if len(matches) == 1 else None


def _go_profile(path: Path, source_paths: set[str], root: Path) -> tuple[dict[str, dict[str, int]], list[str]]:
    values: dict[str, dict[str, int]] = {}
    errors: list[str] = []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as exc:
        return {}, [f"cannot read Go profile: {exc}"]
    for number, line in enumerate(lines, 1):
        if not line or line.startswith("mode:"):
            continue
        match = PROFILE_RE.match(line)
        if not match:
            errors.append(f"line {number}: malformed Go profile row")
            continue
        relative = _resolve_profile_path(match.group("file"), source_paths, root)
        if relative is None:
            errors.append(f"line {number}: unowned Go profile path")
            continue
        statements = int(match.group("statements"))
        count = int(match.group("count"))
        row = values.setdefault(relative, {"statements": 0, "covered_statements": 0})
        row["statements"] += statements
        if count > 0:
            row["covered_statements"] += statements
    return values, errors


def _python_profile(path: Path, source_paths: set[str], root: Path) -> tuple[dict[str, dict[str, int]], list[str]]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [f"cannot read Python coverage JSON: {exc}"]
    if not isinstance(raw, dict) or not isinstance(raw.get("files"), dict):
        return {}, ["Python coverage JSON has no file map"]
    values: dict[str, dict[str, int]] = {}
    errors: list[str] = []
    for name, entry in raw["files"].items():
        if not isinstance(name, str) or not isinstance(entry, dict):
            errors.append("Python coverage contains an invalid file entry")
            continue
        relative = _resolve_profile_path(name, source_paths, root)
        if relative is None:
            errors.append(f"unowned Python coverage path: {name}")
            continue
        summary = entry.get("summary")
        if not isinstance(summary, dict):
            errors.append(f"Python coverage has no summary: {name}")
            continue
        statements = int(summary.get("num_statements", 0))
        covered = int(summary.get("covered_lines", 0))
        branches = int(summary.get("num_branches", 0))
        covered_branches = int(summary.get("covered_branches", 0))
        values[relative] = {
            "units": statements + branches,
            "covered_units": covered + covered_branches,
        }
    return values, errors


def _go_profile_metadata(
    path: Path, source_paths: set[str], root: Path
) -> tuple[set[str], set[str], list[str]]:
    """Read zero-statement and current-platform exclusions from a gate report."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return set(), set(), [f"cannot read Go coverage metadata: {exc}"]
    if not isinstance(raw, dict):
        return set(), set(), ["Go coverage metadata is not an object"]
    payload = raw.get("go", raw)
    if not isinstance(payload, dict):
        return set(), set(), ["Go coverage metadata has no report object"]
    zero: set[str] = set()
    excluded: set[str] = set()
    errors: list[str] = []
    for key, destination in (
        ("zero_statement_files", zero),
        ("current_platform_excluded_files", excluded),
    ):
        values = payload.get(key, [])
        if not isinstance(values, list):
            errors.append(f"Go coverage metadata field is not a list: {key}")
            continue
        for value in values:
            if not isinstance(value, str):
                errors.append(f"Go coverage metadata has a non-string path: {key}")
                continue
            relative = _resolve_profile_path(value, source_paths, root)
            if relative is None:
                errors.append(f"unowned Go coverage metadata path: {value}")
                continue
            destination.add(relative)
    return zero, excluded, errors


def _profile_result(
    language: str,
    relative: str,
    go_values: Mapping[str, Mapping[str, int]],
    python_values: Mapping[str, Mapping[str, int]],
    go_supplied: bool,
    python_supplied: bool,
    go_zero_files: set[str] | None = None,
    go_excluded_files: set[str] | None = None,
) -> dict[str, Any]:
    if language == "go":
        if relative in (go_excluded_files or set()):
            return {"status": "platform-excluded", "reason": "excluded by the current Go build constraints"}
        if relative in (go_zero_files or set()):
            return {"status": "zero-executable", "units": 0, "covered_units": 0, "percent": 100.0}
        row = go_values.get(relative)
        if row:
            total = int(row["statements"])
            covered = int(row["covered_statements"])
            return {"status": "profiled", "units": total, "covered_units": covered, "percent": round(covered * 100 / total, 2) if total else 100.0}
        return {"status": "missing" if go_supplied else "not-provided"}
    if language == "python":
        row = python_values.get(relative)
        if row:
            total = int(row["units"])
            covered = int(row["covered_units"])
            return {"status": "profiled", "units": total, "covered_units": covered, "percent": round(covered * 100 / total, 2) if total else 100.0}
        return {"status": "missing" if python_supplied else "not-provided"}
    return {"status": "not-applicable"}


def _ratio(numerator: int, denominator: int) -> float | None:
    return round(numerator * 100 / denominator, 2) if denominator else None


def build_index(
    root: Path,
    *,
    output: Path | None = None,
    base: str | None = None,
    go_profile: Path | None = None,
    go_report: Path | None = None,
    python_report: Path | None = None,
) -> dict[str, Any]:
    root = _validate_root(root)
    files, exclusions = _walk_files(root, output)
    stats = {_relative(path, root): _file_stats(path, root) for path in files}
    source_paths = sorted(relative for relative in stats if _language(Path(relative)))
    source_set = set(source_paths)
    documentation_paths = [relative for relative in stats if Path(relative).suffix.lower() in DOCUMENT_SUFFIXES]
    documentation = {relative: _text(root / relative).lower() for relative in documentation_paths}
    test_texts = {
        relative: _text(root / relative).lower()
        for relative in source_paths
        if _is_test_path(relative)
    }
    go_package_docs = _go_package_documentation(root, source_paths)
    go_package_names = {
        relative: _go_package_name(root / relative)
        for relative in source_paths
        if Path(relative).suffix.lower() == ".go"
    }
    identity = _git_identity(root)
    delta = _git_changes(root, base, identity)
    go_values: dict[str, dict[str, int]] = {}
    python_values: dict[str, dict[str, int]] = {}
    go_zero_files: set[str] = set()
    go_excluded_files: set[str] = set()
    profile_errors: list[str] = []
    if go_profile is not None:
        go_values, errors = _go_profile(go_profile, {path for path in source_set if _language(Path(path)) == "go"}, root)
        profile_errors.extend(errors)
    if go_report is not None:
        go_zero_files, go_excluded_files, errors = _go_profile_metadata(
            go_report, {path for path in source_set if _language(Path(path)) == "go"}, root
        )
        profile_errors.extend(errors)
    if python_report is not None:
        python_values, errors = _python_profile(python_report, {path for path in source_set if _language(Path(path)) == "python"}, root)
        profile_errors.extend(errors)

    records: list[dict[str, Any]] = []
    for relative in source_paths:
        path = root / relative
        language = _language(path)
        assert language is not None
        tests = _test_evidence(
            relative,
            language,
            source_paths,
            test_texts,
            go_package_names.get(relative),
        )
        docs = _documentation_evidence(relative, path, documentation, root, go_package_docs)
        is_test = _is_test_path(relative)
        record = dict(stats[relative])
        record.update(
            {
                "language": language,
                "generated": _generated(path),
                "is_test": is_test,
                "tests": {
                    "status": "test-file" if is_test else ("associated" if tests else "gap"),
                    "files": [] if is_test else tests,
                },
                "documentation": {"status": "not-applicable", "evidence": [], "method": "test-file"}
                if is_test
                else docs,
                "profile": {"status": "not-applicable"}
                if is_test
                else _profile_result(
                    language,
                    relative,
                    go_values,
                    python_values,
                    go_profile is not None,
                    python_report is not None,
                    go_zero_files,
                    go_excluded_files,
                ),
            }
        )
        records.append(record)

    changed_paths = {item["path"] for item in delta.get("items", [])}
    gaps: list[dict[str, Any]] = []
    for record in records:
        changed = record["path"] in changed_paths
        if record["generated"] or record["is_test"]:
            continue
        if record["tests"]["status"] != "associated":
            gaps.append({"kind": "test", "path": record["path"], "priority": "high" if changed else "normal", "detail": "no matching test file was found"})
        if record["documentation"]["status"] != "evidence":
            gaps.append({"kind": "documentation", "path": record["path"], "priority": "high" if changed else "normal", "detail": "no nearby or referenced documentation evidence was found"})
        if record["language"] in {"go", "python"}:
            profile = record["profile"]
            if profile["status"] in {"missing", "not-provided"}:
                gaps.append({"kind": "profiling", "path": record["path"], "priority": "high" if changed else "normal", "detail": "no matching Go or branch-aware Python profile entry was supplied"})
            elif profile["status"] == "profiled":
                units = int(profile.get("units", 0))
                covered_units = int(profile.get("covered_units", 0))
                if covered_units < units:
                    gaps.append({"kind": "profiling", "path": record["path"], "priority": "high" if changed else "normal", "detail": f"profile leaves {units - covered_units} of {units} executable units uncovered"})
    gaps.sort(key=lambda item: (item["priority"] != "high", item["kind"], item["path"]))

    applicable = [record for record in records if not record["generated"] and not record["is_test"]]
    tested = sum(record["tests"]["status"] == "associated" for record in applicable)
    documented = sum(record["documentation"]["status"] == "evidence" for record in applicable)
    profile_applicable = [
        record
        for record in applicable
        if record["language"] in {"go", "python"}
        and record["profile"]["status"] not in {"platform-excluded", "zero-executable"}
    ]
    profiled = sum(record["profile"]["status"] == "profiled" for record in profile_applicable)
    profile_units = sum(int(record["profile"].get("units", 0)) for record in profile_applicable)
    profile_covered = sum(int(record["profile"].get("covered_units", 0)) for record in profile_applicable)
    summary = {
        "source_files": len(applicable),
        "generated_source_files": sum(record["generated"] for record in records),
        "test_evidence_files": tested,
        "documentation_evidence_files": documented,
        "profiling_applicable_files": len(profile_applicable),
        "profiled_files": profiled,
        "test_evidence_percent": _ratio(tested, len(applicable)),
        "documentation_evidence_percent": _ratio(documented, len(applicable)),
        "profiling_file_percent": _ratio(profiled, len(profile_applicable)),
        "profiling_scope_excluded_files": sum(
            record["profile"]["status"] == "platform-excluded" for record in applicable
        ),
        "profiling_zero_executable_files": sum(
            record["profile"]["status"] == "zero-executable" for record in applicable
        ),
        "profile_units": profile_units,
        "profile_covered_units": profile_covered,
        "profile_statement_or_branch_percent": _ratio(profile_covered, profile_units),
        "profile_errors": len(profile_errors),
        "open_gaps": len(gaps),
    }
    return {
        "schema_version": "1.0.0",
        "generated_by": {"tool": "rkc quality-index", "version": SCRIPT_VERSION},
        "project": PROJECT,
        "publisher": PUBLISHER,
        "license": {"spdx": LICENSE, "attribution": "NeuroForgeIO and RKC contributors"},
        "source": {"root": ".", "git": identity, "base": base},
        "policy": {
            "description": "Heuristic associations are triage evidence, not proof of semantic completeness.",
            "excluded_components": sorted(EXCLUDED_COMPONENTS),
            "profile_semantics": "Go statement blocks and Python lines plus branches when supplied",
        },
        "summary": summary,
        "files": records,
        "documentation": [stats[path] for path in documentation_paths],
        "exclusions": exclusions,
        "deltas": delta,
        "profile_errors": sorted(profile_errors),
        "gaps": gaps,
    }


def render_markdown(index: Mapping[str, Any]) -> str:
    summary = index["summary"]
    lines = [
        "# RKC quality index",
        "",
        f"Generated by `{index['generated_by']['tool']}` {index['generated_by']['version']} for **{index['publisher']} / {index['project']}**.",
        "",
        "> This is a deterministic audit and triage report.  Evidence percentages are not a claim of semantic 100% coverage; inspect the explicit gaps and supply fresh profiles for release decisions.",
        "",
        "## Summary",
        "",
        "| Measure | Result |",
        "| --- | ---: |",
        f"| Source files | {summary['source_files']} |",
        f"| Test evidence | {summary['test_evidence_percent'] if summary['test_evidence_percent'] is not None else 'n/a'}% |",
        f"| Documentation evidence | {summary['documentation_evidence_percent'] if summary['documentation_evidence_percent'] is not None else 'n/a'}% |",
        f"| Profiled Go/Python files | {summary['profiling_file_percent'] if summary['profiling_file_percent'] is not None else 'n/a'}% |",
        f"| Profile units covered | {summary['profile_statement_or_branch_percent'] if summary['profile_statement_or_branch_percent'] is not None else 'n/a'}% |",
        f"| Platform-excluded profile files | {summary['profiling_scope_excluded_files']} |",
        f"| Zero-executable profile files | {summary['profiling_zero_executable_files']} |",
        f"| Profile errors | {summary['profile_errors']} |",
        f"| Open gaps | {summary['open_gaps']} |",
        "",
        "## Open gaps",
        "",
    ]
    gaps = index["gaps"]
    if gaps:
        lines.extend(f"- **{gap['priority']} {gap['kind']}** `{gap['path']}` — {gap['detail']}." for gap in gaps)
    else:
        lines.append("- No gaps were detected by the configured evidence rules.")
    profile_errors = index.get("profile_errors", [])
    if profile_errors:
        lines.extend(["", "## Profile errors", ""])
        lines.extend(f"- {error}" for error in profile_errors)
    lines.extend(["", "## Source inventory", "", "| Path | Language | Tests | Docs | Profile |", "| --- | --- | --- | --- | --- |"])
    for record in index["files"]:
        lines.append(
            f"| `{record['path']}` | {record['language']} | {record['tests']['status']} | {record['documentation']['status']} | {record['profile']['status']} |"
        )
    lines.extend(["", "## Changed paths", ""])
    changes = index["deltas"].get("items", [])
    if changes:
        lines.extend(f"- `{item['status']}` `{item['path']}`" for item in changes)
    else:
        lines.append("- No Git changes were available for this run.")
    lines.extend(
        [
            "",
            "## Reproducibility",
            "",
            "The JSON file beside this document contains SHA-256, byte, and line metadata for every admitted source and documentation file. Re-run `make quality-index` after edits; pass `--base <ref>`, `--go-profile <path>`, `--go-report <path>`, or `--python-report <path>` for a bounded delta or profile view.",
            "",
            f"RKC-owned code and this report are released under the [MIT License](../LICENSE); retain the license and credit **{PUBLISHER} / RKC contributors** in redistributed products.",
            "",
        ]
    )
    return "\n".join(lines)


def _safe_output_directory(path: Path) -> Path:
    """Create an output directory without traversing symlinked ancestors."""
    try:
        info = os.lstat(path)
    except FileNotFoundError:
        missing: list[Path] = []
        ancestor = path
        while True:
            try:
                ancestor_info = os.lstat(ancestor)
            except FileNotFoundError:
                missing.append(ancestor)
                parent = ancestor.parent
                if parent == ancestor:
                    raise QualityIndexError(f"output parent does not exist: {path}")
                ancestor = parent
                continue
            if stat.S_ISLNK(ancestor_info.st_mode) or not stat.S_ISDIR(ancestor_info.st_mode):
                raise QualityIndexError(f"output must have real directory ancestors: {path}")
            for directory in reversed(missing):
                directory.mkdir(mode=0o755)
                created = os.lstat(directory)
                if stat.S_ISLNK(created.st_mode) or not stat.S_ISDIR(created.st_mode):
                    raise QualityIndexError(f"output directory was replaced unsafely: {directory}")
            return path.resolve()
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISDIR(info.st_mode):
        raise QualityIndexError(f"output must be a real directory: {path}")
    return path.resolve()


def write_index(index: Mapping[str, Any], output: Path) -> tuple[Path, Path]:
    destination = _safe_output_directory(output)
    payload = json.dumps(index, indent=2, sort_keys=True) + "\n"
    markdown = render_markdown(index)
    temporary: list[Path] = []
    try:
        for name, content in (("index.json", payload), ("index.md", markdown)):
            fd, raw = tempfile.mkstemp(prefix=f".{name}.", dir=destination)
            temporary_path = Path(raw)
            temporary.append(temporary_path)
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(temporary_path, 0o644)
            os.replace(temporary_path, destination / name)
            temporary.remove(temporary_path)
    finally:
        for path in temporary:
            try:
                path.unlink()
            except FileNotFoundError:
                pass
    return destination / "index.json", destination / "index.md"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="folder to index (default: current folder)")
    parser.add_argument("--output", type=Path, default=None, help=f"output directory (default: <root>/{DEFAULT_OUTPUT_NAME})")
    parser.add_argument("--base", help="Git ref used for the committed delta comparison")
    parser.add_argument("--go-profile", type=Path, help="optional merged Go coverprofile")
    parser.add_argument(
        "--go-report",
        type=Path,
        help="optional coverage-gate JSON report for zero-statement and platform-excluded Go files",
    )
    parser.add_argument("--python-report", type=Path, help="optional Coverage.py JSON report")
    parser.add_argument(
        "--fail-on-gaps",
        action="store_true",
        help="return a non-zero status when the configured evidence rules find any gap",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    root = arguments.root
    output = arguments.output or root / DEFAULT_OUTPUT_NAME
    try:
        index = build_index(
            root,
            output=output,
            base=arguments.base,
            go_profile=arguments.go_profile,
            go_report=arguments.go_report,
            python_report=arguments.python_report,
        )
        json_path, markdown_path = write_index(index, output)
    except (QualityIndexError, OSError, ValueError) as exc:
        print(f"quality index failed closed: {exc}", file=sys.stderr)
        return 1
    profile_errors = index.get("profile_errors", [])
    result = {"ok": not profile_errors and not (arguments.fail_on_gaps and index["gaps"]), "json": str(json_path), "markdown": str(markdown_path), "summary": index["summary"]}
    print(json.dumps(result, sort_keys=True))
    if profile_errors:
        print(
            f"quality index: {len(profile_errors)} profile error(s) were recorded; supplied evidence is not trustworthy",
            file=sys.stderr,
        )
        return 1
    if arguments.fail_on_gaps and index["gaps"]:
        print(
            f"quality index: {len(index['gaps'])} evidence gap(s) remain; see {markdown_path}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
