from __future__ import annotations

import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

try:
    from scripts import quality_index as index
except ModuleNotFoundError as exc:
    if exc.name != "scripts":
        raise
    import quality_index as index


class QualityIndexTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="rkc-quality-index-test-")
        self.root = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def write(self, relative: str, content: str = "x\n") -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def test_path_helpers_and_safe_walk(self) -> None:
        self.assertEqual(index._normalise_stem("A_b.c"), "abc")
        self.assertEqual(index._language(Path("thing.GO")), "go")
        self.assertIsNone(index._language(Path("thing.txt")))
        self.assertTrue(index._is_test_path("tests/test_api.py"))
        self.assertTrue(index._is_test_path("src/api.spec.ts"))
        self.assertTrue(index._is_test_path("src/api_test.go"))
        self.assertFalse(index._is_test_path("src/api.go"))
        self.assertTrue(index._is_excluded("dist/file.go", None))
        self.assertTrue(index._is_excluded("reports/index.json", "reports"))
        self.assertFalse(index._is_excluded("src/main.go", "reports"))
        self.assertEqual(index._ratio(1, 2), 50.0)
        self.assertIsNone(index._ratio(0, 0))

        self.write("src/main.go", "package src\n")
        self.write("docs/readme.md", "# docs\n")
        self.write("dist/ignored.go", "package ignored\n")
        self.write(".rkc/cache.py", "ignored\n")
        outside = self.root / "outside"
        outside.mkdir()
        if hasattr(os, "symlink"):
            (self.root / "src" / "link.go").symlink_to(outside / "missing.go")
            (self.root / "linked-dir").symlink_to(outside, target_is_directory=True)
        files, exclusions = index._walk_files(self.root, self.root / "reports")
        paths = [index._relative(path, self.root) for path in files]
        self.assertEqual(paths, ["docs/readme.md", "src/main.go"])
        if hasattr(os, "symlink"):
            self.assertEqual(
                exclusions,
                [
                    {"path": "linked-dir", "reason": "symlink-directory"},
                    {"path": "src/link.go", "reason": "symlink-file"},
                ],
            )

        with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
            index._validate_root(self.root / "missing")
        file_path = self.write("not-a-root", "file")
        with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
            index._validate_root(file_path)

    def test_file_stats_generated_and_test_documentation_evidence(self) -> None:
        source = self.write("pkg/api.go", "package pkg\nfunc API() {}\n")
        self.write("pkg/api_test.go", "package pkg\nfunc TestAPI() {}\n")
        self.write("pkg/doc.go", "// Package pkg documents the package.\npackage pkg\n")
        python = self.write("tools/worker.py", '"""Worker documentation."""\nprint(1)\n')
        self.write("tools/test_worker.py", "def test_worker():\n    pass\n")
        undocumented = self.write("tools/secret.py", "print('secret')")
        generated = self.write("generated/out.go", "// Code generated by fixture. DO NOT EDIT.\npackage out\n")
        runtime_generated = self.write(
            "tools/runtime.py", "print('Generated by RKC at runtime')\n"
        )
        self.write("docs/guide.md", "See `pkg/api.go` and worker.py for details.\n")

        stats = index._file_stats(undocumented, self.root)
        self.assertEqual(stats["lines"], 1)
        self.assertEqual(stats["bytes"], len(b"print('secret')"))
        self.assertEqual(index._text(self.root / "missing.txt"), "")
        self.assertFalse(index._generated(source))
        self.assertTrue(index._generated(generated))
        self.assertFalse(index._generated(runtime_generated))
        self.assertEqual(
            index._test_evidence("pkg/api.go", "go", ["pkg/api.go", "pkg/api_test.go"]),
            ["pkg/api_test.go"],
        )
        self.assertEqual(
            index._test_evidence("tools/worker.py", "python", ["tools/worker.py", "tools/test_worker.py"]),
            ["tools/test_worker.py"],
        )
        documentation = {"docs/guide.md": index._text(self.root / "docs/guide.md").lower()}
        go_docs = index._documentation_evidence("pkg/api.go", source, documentation, self.root)
        self.assertEqual(go_docs["status"], "evidence")
        self.assertIn("pkg/doc.go", go_docs["evidence"])
        py_docs = index._documentation_evidence("tools/worker.py", python, documentation, self.root)
        self.assertIn("in-source-docstring", py_docs["evidence"])
        no_docs = index._documentation_evidence("tools/secret.py", undocumented, {}, self.root)
        self.assertEqual(no_docs["status"], "gap")
        invalid = self.write("tools/invalid.py", "def broken(:\n")
        self.assertIn("syntax-unavailable", index._documentation_evidence("tools/invalid.py", invalid, {}, self.root)["evidence"])

    def test_package_comments_and_cross_language_test_references_are_evidence(self) -> None:
        package_doc = self.write(
            "pkg/comment.go",
            "// Package comment documents the package without requiring doc.go.\n"
            "package comment\n",
        )
        source = self.write("pkg/service.go", "package comment\n\nfunc Run() {}\n")
        package_docs = index._go_package_documentation(
            self.root, ["pkg/comment.go", "pkg/service.go"]
        )
        docs = index._documentation_evidence(
            "pkg/service.go", source, {}, self.root, package_docs
        )
        self.assertEqual(docs["status"], "evidence")
        self.assertIn("pkg/comment.go", docs["evidence"])
        self.assertIn("Go-package-comment", docs["method"])

        shell = self.write("scripts/release.sh", "#!/bin/sh\nexit 0\n")
        test = self.write(
            "scripts/test_release.py",
            '"scripts/release.sh" is exercised by this harness.\n',
        )
        del shell, test
        evidence = index._test_evidence(
            "scripts/release.sh",
            "shell",
            ["scripts/release.sh", "scripts/test_release.py"],
            {"scripts/test_release.py": '"scripts/release.sh" is exercised'},
        )
        self.assertEqual(evidence, ["scripts/test_release.py"])

        external_test = self.write(
            "pkg/api_test.go",
            "package other\n\nfunc TestAPI() { comment.Run() }\n",
        )
        del external_test
        package_evidence = index._test_evidence(
            "pkg/service.go",
            "go",
            ["pkg/service.go", "pkg/api_test.go"],
            {"pkg/api_test.go": "package other\nfunc TestAPI() { comment.Run() }"},
            "comment",
        )
        self.assertEqual(package_evidence, ["pkg/api_test.go"])

    def test_profile_parsers_and_path_resolution(self) -> None:
        go = self.write("pkg/api.go", "package pkg\nfunc API() {}\n")
        py = self.write("tools/worker.py", "print(1)\n")
        source_go = {"pkg/api.go"}
        self.assertEqual(index._resolve_profile_path("pkg/api.go", source_go, self.root), "pkg/api.go")
        self.assertEqual(index._resolve_profile_path(str(go), source_go, self.root), "pkg/api.go")
        self.assertIsNone(index._resolve_profile_path("other/api.go", {"a/api.go", "b/api.go"}, self.root))
        go_profile = self.write(
            "go.out",
            "mode: set\n"
            "example/module/pkg/api.go:2.1,2.18 3 0\n"
            "example/module/pkg/api.go:2.1,2.18 3 1\n"
            "example/module/pkg/api.go:3.1,4.2 2 0\n"
            "bad row\n"
            "other.go:1.1,1.2 1 1\n",
        )
        values, errors = index._go_profile(go_profile, source_go, self.root)
        self.assertEqual(
            values["pkg/api.go"],
            {
                "statements": 5,
                "covered_statements": 3,
                "uncovered_regions": [
                    {
                        "start_line": 3,
                        "start_column": 1,
                        "end_line": 4,
                        "end_column": 2,
                        "units": 2,
                    }
                ],
            },
        )
        self.assertEqual(len(errors), 2)
        conflicting = self.write(
            "conflicting.out",
            "mode: atomic\n"
            "pkg/api.go:2.1,2.18 1 0\n"
            "pkg/api.go:2.1,2.18 2 1\n"
            "pkg/api.go:4.2,3.1 1 0\n",
        )
        conflicting_values, conflicting_errors = index._go_profile(
            conflicting, source_go, self.root
        )
        self.assertEqual(conflicting_values, {})
        self.assertEqual(len(conflicting_errors), 2)
        unsupported = self.write("unsupported.out", "mode: mystery\n")
        self.assertIn(
            "unsupported", index._go_profile(unsupported, source_go, self.root)[1][0]
        )
        no_header = self.write("no-header.out", "pkg/api.go:1.1,1.2 1 0\n")
        self.assertIn(
            "mode header", index._go_profile(no_header, source_go, self.root)[1][0]
        )
        missing = self.root / "missing.out"
        values, errors = index._go_profile(missing, source_go, self.root)
        self.assertEqual(values, {})
        self.assertTrue(errors)

        python_report = self.write(
            "python.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        str(py): {
                            "missing_lines": [1],
                            "missing_branches": [[1, -1]],
                            "summary": {
                                "num_statements": 4,
                                "covered_lines": 3,
                                "num_branches": 2,
                                "covered_branches": 1,
                            }
                        },
                        "unknown.py": {"summary": {}},
                        "bad.py": {},
                        "not-an-object": "bad",
                    }
                }
            ),
        )
        values, errors = index._python_profile(
            python_report, {"tools/worker.py"}, self.root
        )
        self.assertEqual(
            values["tools/worker.py"],
            {
                "units": 6,
                "covered_units": 4,
                "uncovered_lines": [1],
                "uncovered_branches": [[1, -1]],
            },
        )
        self.assertEqual(len(errors), 3)
        line_only = self.write(
            "line-only.json",
            json.dumps({"meta": {"branch_coverage": False}, "files": {}}),
        )
        self.assertIn(
            "branch coverage", index._python_profile(line_only, set(), self.root)[1][0]
        )
        inconsistent = self.write(
            "inconsistent.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 1,
                                "covered_lines": 2,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        self.assertIn(
            "denominator",
            index._python_profile(
                inconsistent, {"tools/worker.py"}, self.root
            )[1][0],
        )
        missing_detail = self.write(
            "missing-detail.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 2,
                                "covered_lines": 1,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        self.assertIn(
            "missing-line",
            index._python_profile(
                missing_detail, {"tools/worker.py"}, self.root
            )[1][0],
        )
        invalid_json = self.write("invalid.json", "not-json")
        self.assertTrue(index._python_profile(invalid_json, set(), self.root)[1])
        no_files = self.write("no-files.json", "{}")
        self.assertIn("file map", index._python_profile(no_files, set(), self.root)[1][0])
        self.assertEqual(
            index._profile_result("go", "pkg/api.go", go_values={}, python_values={}, go_supplied=False, python_supplied=False)["status"],
            "not-provided",
        )
        self.assertEqual(
            index._profile_result("python", "tools/worker.py", {}, {}, False, True)["status"],
            "missing",
        )
        profiled = index._profile_result(
            "go",
            "pkg/api.go",
            {
                "pkg/api.go": {
                    "statements": 2,
                    "covered_statements": 1,
                    "uncovered_regions": [
                        {
                            "start_line": 2,
                            "start_column": 1,
                            "end_line": 2,
                            "end_column": 18,
                            "units": 1,
                        }
                    ],
                }
            },
            {},
            True,
            False,
        )
        self.assertEqual(profiled["percent"], 50.0)
        self.assertEqual(profiled["uncovered"]["regions"][0]["start_line"], 2)
        zero_report = self.write(
            "go-summary.json",
            json.dumps(
                {
                    "go": {
                        "zero_statement_files": ["pkg/api.go"],
                        "current_platform_excluded_files": [],
                    }
                }
            ),
        )
        zero, excluded, metadata_errors = index._go_profile_metadata(
            zero_report, {"pkg/api.go"}, self.root
        )
        self.assertEqual(zero, {"pkg/api.go"})
        self.assertEqual(excluded, set())
        self.assertEqual(metadata_errors, [])
        self.assertEqual(
            index._profile_result(
                "go", "pkg/api.go", {}, {}, True, False, zero, excluded
            )["status"],
            "zero-executable",
        )
        bad_metadata = self.write(
            "bad-go-summary.json",
            json.dumps({"go": {"zero_statement_files": "bad"}}),
        )
        self.assertTrue(index._go_profile_metadata(bad_metadata, {"pkg/api.go"}, self.root)[2])
        self.assertEqual(index._profile_result("rust", "x.rs", {}, {}, False, False)["status"], "not-applicable")

    def test_git_change_parser_and_identity(self) -> None:
        self.assertEqual(
            index._parse_git_changes("M\0src/a.go\0R100\0old.go\0new.go\0C050\0a.go\0b.go\0"),
            [
                {"status": "M", "path": "src/a.go"},
                {"status": "renamed", "path": "new.go", "previous_path": "old.go"},
                {"status": "copied", "path": "b.go", "previous_path": "a.go"},
            ],
        )
        with self.assertRaisesRegex(index.QualityIndexError, "incomplete"):
            index._parse_git_changes("R100\0old.go\0")
        identity = index._git_identity(self.root)
        self.assertEqual(identity["status"], "unavailable")

        self.run_git("init", "-q", "-b", "main")
        self.run_git("config", "user.email", "rkc-quality@example.invalid")
        self.run_git("config", "user.name", "RKC quality")
        self.write("src/main.go", "package src\n")
        self.run_git("add", "src/main.go")
        self.run_git("commit", "-q", "-m", "fixture")
        identity = index._git_identity(self.root)
        self.assertEqual(identity["status"], "available")
        root_commit = identity["commit"]
        empty_tree = subprocess.run(
            ["git", "-C", str(self.root), "mktree"],
            check=True,
            input="",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        root_delta = index._git_changes(self.root, empty_tree, identity)
        self.assertEqual(root_delta["status"], "available")
        self.assertEqual(root_delta["scope"], f"{empty_tree}..HEAD")
        self.assertEqual(
            root_delta["items"], [{"status": "A", "path": "src/main.go"}]
        )
        root_index = index.build_index(self.root, base=empty_tree)
        self.assertEqual(root_index["deltas"], root_delta)
        self.assertTrue(root_index["gaps"])
        self.assertTrue(
            all(gap["priority"] == "high" for gap in root_index["gaps"])
        )

        self.write("src/main.go", "package src\nfunc Main() {}\n")
        self.write("new.py", "print(1)\n")
        delta = index._git_changes(self.root, None, identity)
        self.assertEqual(delta["status"], "available")
        self.assertEqual([item["path"] for item in delta["items"]], ["new.py", "src/main.go"])
        self.run_git("add", "new.py", "src/main.go")
        self.run_git("commit", "-q", "-m", "second")
        committed_delta = index._git_changes(
            self.root, root_commit, index._git_identity(self.root)
        )
        self.assertEqual(committed_delta["status"], "available")
        self.assertEqual(committed_delta["scope"], f"{root_commit}..HEAD")
        self.assertEqual(
            committed_delta["items"],
            [
                {"status": "A", "path": "new.py"},
                {"status": "M", "path": "src/main.go"},
            ],
        )
        bad = index._git_changes(self.root, "does-not-exist", identity)
        self.assertEqual(bad["status"], "unavailable")

    def test_ci_quality_index_has_a_commit_delta_contract(self) -> None:
        workflow = (
            Path(__file__).resolve().parents[1] / ".github" / "workflows" / "ci.yml"
        ).read_text(encoding="utf-8")
        self.assertIn("fetch-depth: 0", workflow)
        self.assertIn(
            "RKC_QUALITY_BASE: ${{ github.event.pull_request.base.sha || github.event.before }}",
            workflow,
        )
        self.assertIn("quality_base=$(git mktree </dev/null)", workflow)
        self.assertIn(
            'git rev-parse --verify "${quality_base}^{tree}"', workflow
        )
        self.assertIn('--base "$quality_base"', workflow)

    def run_git(self, *arguments: str) -> None:
        subprocess.run(["git", "-C", str(self.root), *arguments], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    def test_build_render_write_and_main_for_arbitrary_folder(self) -> None:
        self.write("src/main.go", "package src\nfunc Main() {}\n")
        self.write("src/main_test.go", "package src\nfunc TestMain() {}\n")
        self.write("src/types.go", "package src\ntype Record struct{}\n")
        self.write("tools/worker.py", '"""worker docs"""\nprint(1)\n')
        self.write("docs/guide.md", "`src/main.go` and worker.py are documented.\n")
        output = self.root / "quality"
        go_profile = self.write("profiles/go.out", "mode: set\nsrc/main.go:2.1,2.18 2 1\n")
        go_report = self.write(
            "profiles/go-summary.json",
            json.dumps(
                {
                    "go": {
                        "zero_statement_files": ["src/types.go"],
                        "current_platform_excluded_files": [],
                    }
                }
            ),
        )
        python_report = self.write(
            "profiles/python.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 2,
                                "covered_lines": 2,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        built = index.build_index(
            self.root,
            output=output,
            go_profile=go_profile,
            go_report=go_report,
            python_report=python_report,
        )
        self.assertFalse(any(record["path"].startswith("quality/") for record in built["files"]))
        self.assertEqual(built["project"], "RKC")
        self.assertEqual(built["publisher"], "NeuroForgeIO")
        self.assertEqual(built["license"]["spdx"], "MIT")
        self.assertEqual(built["summary"]["profiling_file_percent"], 100.0)
        self.assertEqual(built["summary"]["profile_uncovered_units"], 0)
        self.assertEqual(built["summary"]["profiling_zero_executable_files"], 1)
        self.assertEqual(
            next(record for record in built["files"] if record["path"] == "src/types.go")[
                "profile"
            ]["status"],
            "zero-executable",
        )
        self.assertTrue(any(record["is_test"] for record in built["files"]))
        self.assertEqual(
            next(record for record in built["files"] if record["path"] == "src/main.go")[
                "documentation"
            ]["status"],
            "evidence",
        )
        markdown = index.render_markdown(built)
        self.assertIn("RKC quality index", markdown)
        self.assertIn("MIT License", markdown)
        json_path, markdown_path = index.write_index(built, output)
        self.assertTrue(json_path.is_file())
        self.assertTrue(markdown_path.is_file())
        self.assertEqual(json.loads(json_path.read_text(encoding="utf-8"))["schema_version"], "1.0.0")
        self.assertEqual(index.main(["--root", str(self.root), "--output", str(output)]), 0)
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            self.assertEqual(index.main(["--root", str(self.root / "missing")]), 1)
            self.assertIn("failed closed", errors.getvalue())
        if hasattr(os, "symlink"):
            linked = self.root / "linked-output"
            linked.symlink_to(output, target_is_directory=True)
            with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
                index.write_index(built, linked)
            parent_link = self.root / "parent-link"
            parent_link.symlink_to(self.root, target_is_directory=True)
            with self.assertRaisesRegex(index.QualityIndexError, "real directory ancestors"):
                index.write_index(built, parent_link / "nested-output")

    def test_main_can_fail_closed_when_strict_gap_mode_is_requested(self) -> None:
        self.write("src/main.go", "package src\nfunc Main() {}\n")
        output = self.root / "quality"
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            self.assertEqual(
                index.main(
                    [
                        "--root",
                        str(self.root),
                        "--output",
                        str(output),
                        "--fail-on-gaps",
                    ]
                ),
                1,
            )
            self.assertIn("evidence gap", errors.getvalue())
        self.assertTrue((output / "index.json").is_file())

    def test_partial_profiles_and_profile_errors_are_actionable(self) -> None:
        self.write("pkg/main.go", "// Package pkg is a profile fixture.\npackage pkg\nfunc Main() {}\n")
        self.write("pkg/main_test.go", "package pkg\nfunc TestMain() {}\n")
        self.write("docs/pkg.md", "pkg/main.go is covered by the fixture.\n")
        partial = self.write(
            "profiles/partial.out",
            "mode: set\n"
            "pkg/main.go:3.1,3.14 2 0\n",
        )
        report = index.build_index(self.root, go_profile=partial)
        profile_gaps = [gap for gap in report["gaps"] if gap["kind"] == "profiling"]
        self.assertEqual(len(profile_gaps), 1)
        self.assertIn("2 of 2", profile_gaps[0]["detail"])
        self.assertEqual(profile_gaps[0]["uncovered"]["regions"][0]["start_line"], 3)
        self.assertIn("L3:1-L3:14", index.render_markdown(report))

        malformed = self.write("profiles/malformed.out", "mode: set\nnot a profile row\n")
        output = self.root / "strict-quality"
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            status = index.main(
                [
                    "--root",
                    str(self.root),
                    "--output",
                    str(output),
                    "--go-profile",
                    str(malformed),
                ]
            )
        self.assertEqual(status, 1)
        self.assertIn("profile error", errors.getvalue())
        payload = json.loads((output / "index.json").read_text(encoding="utf-8"))
        self.assertTrue(payload["profile_errors"])
        self.assertEqual(payload["summary"]["profile_errors"], 1)
        self.assertIn("Profile errors", (output / "index.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
