from __future__ import annotations

import hashlib
import io
import json
import os
import runpy
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

try:
    from scripts import quality_index as index
except ModuleNotFoundError as exc:
    if exc.name != "scripts":
        raise
    import quality_index as index


class QualityIndexTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="rkc-quality-index-test-")
        self.root = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def write(self, relative: str, content: str = "x\n") -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def test_path_helpers_and_safe_walk(self) -> None:
        self.assertEqual(index._normalise_stem("A_b.c"), "abc")
        self.assertEqual(index._language(Path("thing.GO")), "go")
        self.assertIsNone(index._language(Path("thing.txt")))
        self.assertTrue(index._is_test_path("tests/test_api.py"))
        self.assertTrue(index._is_test_path("src/api.spec.ts"))
        self.assertTrue(index._is_test_path("src/api_test.go"))
        self.assertFalse(index._is_test_path("src/api.go"))
        self.assertTrue(index._is_excluded("dist/file.go", None))
        self.assertTrue(index._is_excluded(".coverage", None))
        self.assertTrue(index._is_excluded("server.test", None))
        self.assertTrue(index._is_excluded("coverage.out", None))
        self.assertTrue(index._is_excluded("reports/index.json", "reports"))
        self.assertFalse(index._is_excluded("src/main.go", "reports"))
        self.assertEqual(index._ratio(1, 2), 50.0)
        self.assertIsNone(index._ratio(0, 0))

        self.write("src/main.go", "package src\n")
        self.write("docs/readme.md", "# docs\n")
        self.write("dist/ignored.go", "package ignored\n")
        self.write(".rkc/cache.py", "ignored\n")
        outside = self.root / "outside"
        outside.mkdir()
        if hasattr(os, "symlink"):
            (self.root / "src" / "link.go").symlink_to(outside / "missing.go")
            (self.root / "linked-dir").symlink_to(outside, target_is_directory=True)
        files, exclusions = index._walk_files(self.root, self.root / "reports")
        paths = [index._relative(path, self.root) for path in files]
        self.assertEqual(paths, ["docs/readme.md", "src/main.go"])
        if hasattr(os, "symlink"):
            self.assertEqual(
                exclusions,
                [
                    {"path": "linked-dir", "reason": "symlink-directory"},
                    {"path": "src/link.go", "reason": "symlink-file"},
                ],
            )

        with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
            index._validate_root(self.root / "missing")
        file_path = self.write("not-a-root", "file")
        with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
            index._validate_root(file_path)

    def test_file_stats_generated_and_test_documentation_evidence(self) -> None:
        source = self.write("pkg/api.go", "package pkg\nfunc API() {}\n")
        self.write("pkg/api_test.go", "package pkg\nfunc TestAPI() {}\n")
        self.write("pkg/doc.go", "// Package pkg documents the package.\npackage pkg\n")
        if hasattr(os, "symlink"):
            (self.root / "pkg" / "linked.go").symlink_to(source)
        python = self.write("tools/worker.py", '"""Worker documentation."""\nprint(1)\n')
        self.write("tools/test_worker.py", "def test_worker():\n    pass\n")
        undocumented = self.write("tools/secret.py", "print('secret')")
        generated = self.write("generated/out.go", "// Code generated by fixture. DO NOT EDIT.\npackage out\n")
        runtime_generated = self.write(
            "tools/runtime.py", "print('Generated by RKC at runtime')\n"
        )
        self.write("docs/guide.md", "See `pkg/api.go` and worker.py for details.\n")

        stats = index._file_stats(undocumented, self.root)
        self.assertEqual(stats["lines"], 1)
        self.assertEqual(stats["bytes"], len(b"print('secret')"))
        self.assertEqual(index._text(self.root / "missing.txt"), "")
        self.assertFalse(index._generated(source))
        self.assertTrue(index._generated(generated))
        self.assertFalse(index._generated(runtime_generated))
        self.assertEqual(
            index._test_evidence("pkg/api.go", "go", ["pkg/api.go", "pkg/api_test.go"]),
            ["pkg/api_test.go"],
        )
        self.assertEqual(
            index._test_evidence("tools/worker.py", "python", ["tools/worker.py", "tools/test_worker.py"]),
            ["tools/test_worker.py"],
        )
        documentation = {"docs/guide.md": index._text(self.root / "docs/guide.md").lower()}
        go_docs = index._documentation_evidence("pkg/api.go", source, documentation, self.root)
        self.assertEqual(go_docs["status"], "evidence")
        self.assertIn("pkg/doc.go", go_docs["evidence"])
        if hasattr(os, "symlink"):
            linked_docs = index._documentation_evidence("pkg/api.go", source, {}, self.root)
            self.assertIn("pkg/doc.go", linked_docs["evidence"])
        py_docs = index._documentation_evidence("tools/worker.py", python, documentation, self.root)
        self.assertIn("in-source-docstring", py_docs["evidence"])
        no_docs = index._documentation_evidence("tools/secret.py", undocumented, {}, self.root)
        self.assertEqual(no_docs["status"], "gap")
        invalid = self.write("tools/invalid.py", "def broken(:\n")
        self.assertIn("syntax-unavailable", index._documentation_evidence("tools/invalid.py", invalid, {}, self.root)["evidence"])

    def test_package_comments_and_cross_language_test_references_are_evidence(self) -> None:
        package_doc = self.write(
            "pkg/comment.go",
            "// Package comment documents the package without requiring doc.go.\n"
            "package comment\n",
        )
        source = self.write("pkg/service.go", "package comment\n\nfunc Run() {}\n")
        package_docs = index._go_package_documentation(
            self.root, ["pkg/comment.go", "pkg/service.go"]
        )
        docs = index._documentation_evidence(
            "pkg/service.go", source, {}, self.root, package_docs
        )
        self.assertEqual(docs["status"], "evidence")
        self.assertIn("pkg/comment.go", docs["evidence"])
        self.assertIn("Go-package-comment", docs["method"])

        shell = self.write("scripts/release.sh", "#!/bin/sh\nexit 0\n")
        test = self.write(
            "scripts/test_release.py",
            '"scripts/release.sh" is exercised by this harness.\n',
        )
        del shell, test
        evidence = index._test_evidence(
            "scripts/release.sh",
            "shell",
            ["scripts/release.sh", "scripts/test_release.py"],
            {"scripts/test_release.py": '"scripts/release.sh" is exercised'},
        )
        self.assertEqual(evidence, ["scripts/test_release.py"])

        external_test = self.write(
            "pkg/api_test.go",
            "package other\n\nfunc TestAPI() { comment.Run() }\n",
        )
        del external_test
        package_evidence = index._test_evidence(
            "pkg/service.go",
            "go",
            ["pkg/service.go", "pkg/api_test.go"],
            {"pkg/api_test.go": "package other\nfunc TestAPI() { comment.Run() }"},
            "comment",
        )
        self.assertEqual(package_evidence, ["pkg/api_test.go"])

    def test_go_ast_exported_documentation_is_exact_and_separate(self) -> None:
        self.write(
            "pkg/api.go",
            "package pkg\n\n"
            "// PublicType is documented.\n"
            "type PublicType struct{}\n"
            "type MissingType struct{}\n\n"
            "type (\n"
            "\t// Grouped is documented.\n"
            "\tGrouped struct{}\n"
            "\tMissingGrouped struct{}\n"
            ")\n\n"
            "// ExportedConstant is documented.\n"
            "const ExportedConstant = 1\n"
            "const MissingConstant = 2\n\n"
            "// DocumentedVariable is documented.\n"
            "var DocumentedVariable = 1\n"
            "var MissingVariable = 2\n\n"
            "// Run is documented.\n"
            "func Run() {}\n"
            "func MissingFunction() {}\n\n"
            "// Do is documented.\n"
            "func (*PublicType) Do() {}\n"
            "func (*PublicType) MissingMethod() {}\n"
            "func hidden() {}\n",
        )
        values = index._go_exported_documentation(self.root, ["pkg/api.go"])
        declarations = values["pkg/api.go"]
        self.assertEqual(len(declarations), 12)
        self.assertEqual(
            {item["symbol"] for item in declarations if not item["documented"]},
            {
                "MissingType",
                "MissingGrouped",
                "MissingConstant",
                "MissingVariable",
                "MissingFunction",
                "(*PublicType).MissingMethod",
            },
        )
        self.assertEqual(
            {item["kind"] for item in declarations},
            {"type", "constant", "variable", "function", "method"},
        )

        report = index.build_index(self.root)
        record = report["files"][0]
        exported = record["go_exported_documentation"]
        self.assertEqual(record["documentation"]["status"], "gap")
        self.assertEqual(exported["status"], "gap")
        self.assertEqual(exported["declarations"], 12)
        self.assertEqual(exported["documented_declarations"], 6)
        self.assertEqual(exported["percent"], 50.0)
        self.assertEqual(len(exported["missing_symbols"]), 6)
        self.assertEqual(report["summary"]["go_exported_declarations"], 12)
        self.assertEqual(report["summary"]["go_exported_documentation_missing"], 6)
        declaration_gaps = [
            gap
            for gap in report["gaps"]
            if gap["kind"] == "go-exported-documentation"
        ]
        self.assertEqual(len(declaration_gaps), 6)
        self.assertTrue(all(gap["line"] > 0 for gap in declaration_gaps))
        self.assertIn("(*PublicType).MissingMethod", index.render_markdown(report))
        self.assertIn("Exported Go declarations documented | 50.0% (6/12)", index.render_markdown(report))

    def test_go_ast_documentation_contract_fails_closed(self) -> None:
        self.assertEqual(index._go_exported_documentation(self.root, []), {})
        with mock.patch.object(index.shutil, "which", return_value=None):
            with self.assertRaisesRegex(index.QualityIndexError, "toolchain"):
                index._go_exported_documentation(self.root, ["pkg/api.go"])

        timeout = subprocess.TimeoutExpired(["go", "run"], 30)
        with mock.patch.object(index.subprocess, "run", side_effect=timeout):
            with self.assertRaisesRegex(index.QualityIndexError, "inspection failed"):
                index._go_exported_documentation(self.root, ["pkg/api.go"])
        failed = subprocess.CompletedProcess([], 1, stdout="", stderr="parser failed\n")
        with mock.patch.object(index.subprocess, "run", return_value=failed):
            with self.assertRaisesRegex(index.QualityIndexError, "parser failed"):
                index._go_exported_documentation(self.root, ["pkg/api.go"])
        invalid_json = subprocess.CompletedProcess([], 0, stdout="not-json", stderr="")
        with mock.patch.object(index.subprocess, "run", return_value=invalid_json):
            with self.assertRaisesRegex(index.QualityIndexError, "valid JSON"):
                index._go_exported_documentation(self.root, ["pkg/api.go"])

        valid_declaration = {
            "symbol": "API",
            "kind": "function",
            "line": 2,
            "column": 1,
            "documented": True,
        }
        malformed_payloads = [
            None,
            {},
            {"version": "wrong", "files": []},
            {"version": "1.0.0", "files": "bad"},
            {"version": "1.0.0", "files": ["bad"]},
            {
                "version": "1.0.0",
                "files": [{"path": "other.go", "declarations": []}],
            },
            {
                "version": "1.0.0",
                "files": [
                    {"path": "pkg/api.go", "declarations": []},
                    {"path": "pkg/api.go", "declarations": []},
                ],
            },
            {
                "version": "1.0.0",
                "files": [{"path": "pkg/api.go", "declarations": "bad"}],
            },
            {
                "version": "1.0.0",
                "files": [{"path": "pkg/api.go", "declarations": [{}]}],
            },
            {
                "version": "1.0.0",
                "files": [
                    {
                        "path": "pkg/api.go",
                        "declarations": [{**valid_declaration, "symbol": ""}],
                    }
                ],
            },
            {
                "version": "1.0.0",
                "files": [
                    {
                        "path": "pkg/api.go",
                        "declarations": [{**valid_declaration, "line": 0}],
                    }
                ],
            },
            {
                "version": "1.0.0",
                "files": [
                    {
                        "path": "pkg/api.go",
                        "declarations": [
                            {**valid_declaration, "documented": "yes"}
                        ],
                    }
                ],
            },
            {
                "version": "1.0.0",
                "files": [
                    {
                        "path": "pkg/api.go",
                        "declarations": [valid_declaration, valid_declaration],
                    }
                ],
            },
            {"version": "1.0.0", "files": []},
        ]
        for payload in malformed_payloads:
            with self.subTest(payload=payload):
                with self.assertRaises(index.QualityIndexError):
                    index._validate_go_documentation_payload(payload, ["pkg/api.go"])

    def test_go_exported_documentation_non_applicable_statuses(self) -> None:
        self.assertEqual(
            index._go_documentation_result(
                "python", generated=False, is_test=False, declarations=None
            ),
            {"status": "not-applicable", "reason": "non-Go source"},
        )
        self.assertEqual(
            index._go_documentation_result(
                "go", generated=True, is_test=False, declarations=None
            )["reason"],
            "generated source",
        )
        self.assertEqual(
            index._go_documentation_result(
                "go", generated=False, is_test=True, declarations=None
            )["reason"],
            "test source",
        )
        empty = index._go_documentation_result(
            "go", generated=False, is_test=False, declarations=[]
        )
        self.assertEqual(empty["status"], "no-exported-declarations")
        self.assertEqual(empty["percent"], 100.0)

    def test_profile_parsers_and_path_resolution(self) -> None:
        go = self.write("pkg/api.go", "package pkg\nfunc API() {}\n")
        py = self.write("tools/worker.py", "print(1)\n")
        source_go = {"pkg/api.go"}
        self.assertEqual(index._resolve_profile_path("pkg/api.go", source_go, self.root), "pkg/api.go")
        self.assertEqual(index._resolve_profile_path(str(go), source_go, self.root), "pkg/api.go")
        self.assertIsNone(index._resolve_profile_path("other/api.go", {"a/api.go", "b/api.go"}, self.root))
        go_profile = self.write(
            "go.out",
            "mode: set\n"
            "example/module/pkg/api.go:2.1,2.18 3 0\n"
            "example/module/pkg/api.go:2.1,2.18 3 1\n"
            "example/module/pkg/api.go:3.1,4.2 2 0\n"
            "bad row\n"
            "other.go:1.1,1.2 1 1\n",
        )
        values, errors = index._go_profile(go_profile, source_go, self.root)
        self.assertEqual(
            values["pkg/api.go"],
            {
                "statements": 5,
                "covered_statements": 3,
                "uncovered_regions": [
                    {
                        "start_line": 3,
                        "start_column": 1,
                        "end_line": 4,
                        "end_column": 2,
                        "units": 2,
                    }
                ],
            },
        )
        self.assertEqual(len(errors), 2)
        conflicting = self.write(
            "conflicting.out",
            "mode: atomic\n"
            "pkg/api.go:2.1,2.18 1 0\n"
            "pkg/api.go:2.1,2.18 2 1\n"
            "pkg/api.go:4.2,3.1 1 0\n",
        )
        conflicting_values, conflicting_errors = index._go_profile(
            conflicting, source_go, self.root
        )
        self.assertEqual(conflicting_values, {})
        self.assertEqual(len(conflicting_errors), 2)
        unsupported = self.write("unsupported.out", "mode: mystery\n")
        self.assertIn(
            "unsupported", index._go_profile(unsupported, source_go, self.root)[1][0]
        )
        no_header = self.write("no-header.out", "pkg/api.go:1.1,1.2 1 0\n")
        self.assertIn(
            "mode header", index._go_profile(no_header, source_go, self.root)[1][0]
        )
        missing = self.root / "missing.out"
        values, errors = index._go_profile(missing, source_go, self.root)
        self.assertEqual(values, {})
        self.assertTrue(errors)

        python_report = self.write(
            "python.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        str(py): {
                            "missing_lines": [1],
                            "missing_branches": [[1, -1]],
                            "summary": {
                                "num_statements": 4,
                                "covered_lines": 3,
                                "num_branches": 2,
                                "covered_branches": 1,
                            }
                        },
                        "unknown.py": {"summary": {}},
                        "bad.py": {},
                        "not-an-object": "bad",
                    }
                }
            ),
        )
        values, errors = index._python_profile(
            python_report, {"tools/worker.py"}, self.root
        )
        self.assertEqual(
            values["tools/worker.py"],
            {
                "units": 6,
                "covered_units": 4,
                "uncovered_lines": [1],
                "uncovered_branches": [[1, -1]],
            },
        )
        self.assertEqual(len(errors), 3)
        line_only = self.write(
            "line-only.json",
            json.dumps({"meta": {"branch_coverage": False}, "files": {}}),
        )
        self.assertIn(
            "branch coverage", index._python_profile(line_only, set(), self.root)[1][0]
        )
        inconsistent = self.write(
            "inconsistent.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 1,
                                "covered_lines": 2,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        self.assertIn(
            "denominator",
            index._python_profile(
                inconsistent, {"tools/worker.py"}, self.root
            )[1][0],
        )
        missing_detail = self.write(
            "missing-detail.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 2,
                                "covered_lines": 1,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        self.assertIn(
            "missing-line",
            index._python_profile(
                missing_detail, {"tools/worker.py"}, self.root
            )[1][0],
        )
        invalid_json = self.write("invalid.json", "not-json")
        self.assertTrue(index._python_profile(invalid_json, set(), self.root)[1])
        no_files = self.write("no-files.json", "{}")
        self.assertIn("file map", index._python_profile(no_files, set(), self.root)[1][0])
        self.assertEqual(
            index._profile_result("go", "pkg/api.go", go_values={}, python_values={}, go_supplied=False, python_supplied=False)["status"],
            "not-provided",
        )
        self.assertEqual(
            index._profile_result("python", "tools/worker.py", {}, {}, False, True)["status"],
            "missing",
        )
        profiled = index._profile_result(
            "go",
            "pkg/api.go",
            {
                "pkg/api.go": {
                    "statements": 2,
                    "covered_statements": 1,
                    "uncovered_regions": [
                        {
                            "start_line": 2,
                            "start_column": 1,
                            "end_line": 2,
                            "end_column": 18,
                            "units": 1,
                        }
                    ],
                }
            },
            {},
            True,
            False,
        )
        self.assertEqual(profiled["percent"], 50.0)
        self.assertEqual(profiled["uncovered"]["regions"][0]["start_line"], 2)
        zero_report = self.write(
            "go-summary.json",
            json.dumps(
                {
                    "go": {
                        "zero_statement_files": ["pkg/api.go"],
                        "current_platform_excluded_files": [],
                    }
                }
            ),
        )
        zero, excluded, metadata_errors = index._go_profile_metadata(
            zero_report, {"pkg/api.go"}, self.root
        )
        self.assertEqual(zero, {"pkg/api.go"})
        self.assertEqual(excluded, set())
        self.assertEqual(metadata_errors, [])
        self.assertEqual(
            index._profile_result(
                "go", "pkg/api.go", {}, {}, True, False, zero, excluded
            )["status"],
            "zero-executable",
        )
        bad_metadata = self.write(
            "bad-go-summary.json",
            json.dumps({"go": {"zero_statement_files": "bad"}}),
        )
        self.assertTrue(index._go_profile_metadata(bad_metadata, {"pkg/api.go"}, self.root)[2])
        self.assertEqual(index._profile_result("rust", "x.rs", {}, {}, False, False)["status"], "not-applicable")

    def test_git_change_parser_and_identity(self) -> None:
        self.assertEqual(
            index._parse_git_changes("M\0src/a.go\0R100\0old.go\0new.go\0C050\0a.go\0b.go\0"),
            [
                {"status": "M", "path": "src/a.go"},
                {"status": "renamed", "path": "new.go", "previous_path": "old.go"},
                {"status": "copied", "path": "b.go", "previous_path": "a.go"},
            ],
        )
        with self.assertRaisesRegex(index.QualityIndexError, "incomplete"):
            index._parse_git_changes("R100\0old.go\0")
        identity = index._git_identity(self.root)
        self.assertEqual(identity["status"], "unavailable")
        self.assertEqual(
            index._git_tracked_paths(self.root, identity)["status"], "unavailable"
        )
        self.assertEqual(
            index._git_stability_token(self.root, identity)["status"],
            "unavailable",
        )

        self.run_git("init", "-q", "-b", "main")
        self.run_git("config", "user.email", "rkc-quality@example.invalid")
        self.run_git("config", "user.name", "RKC quality")
        self.write("src/main.go", "package src\n")
        self.run_git("add", "src/main.go")
        self.run_git("commit", "-q", "-m", "fixture")
        identity = index._git_identity(self.root)
        self.assertEqual(identity["status"], "available")
        self.assertEqual(
            index._git_stability_token(self.root, identity)["status"], "available"
        )
        root_commit = identity["commit"]
        empty_tree = subprocess.run(
            ["git", "-C", str(self.root), "mktree"],
            check=True,
            input="",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        root_delta = index._git_changes(self.root, empty_tree, identity)
        self.assertEqual(root_delta["status"], "available")
        self.assertEqual(root_delta["scope"], f"{empty_tree}..{root_commit}")
        self.assertEqual(
            root_delta["items"], [{"status": "A", "path": "src/main.go"}]
        )
        root_index = index.build_index(self.root, base=empty_tree)
        self.assertEqual(root_index["deltas"], root_delta)
        self.assertEqual(root_index["git_inventory"]["paths"], ["src/main.go"])
        self.assertEqual(root_index["summary"]["tracked_admitted_files"], 1)
        self.assertTrue(root_index["gaps"])
        self.assertTrue(
            all(gap["priority"] == "high" for gap in root_index["gaps"])
        )

        self.write("src/main.go", "package src\nfunc Main() {}\n")
        self.write("new.py", "print(1)\n")
        delta = index._git_changes(self.root, None, identity)
        self.assertEqual(delta["status"], "available")
        self.assertEqual([item["path"] for item in delta["items"]], ["new.py", "src/main.go"])
        self.run_git("add", "new.py", "src/main.go")
        self.run_git("commit", "-q", "-m", "second")
        second_identity = index._git_identity(self.root)
        committed_delta = index._git_changes(self.root, root_commit, second_identity)
        self.assertEqual(committed_delta["status"], "available")
        self.assertEqual(
            committed_delta["scope"], f"{root_commit}..{second_identity['commit']}"
        )
        self.assertEqual(
            committed_delta["items"],
            [
                {"status": "A", "path": "new.py"},
                {"status": "M", "path": "src/main.go"},
            ],
        )
        bad = index._git_changes(self.root, "does-not-exist", identity)
        self.assertEqual(bad["status"], "unavailable")

    def test_ci_quality_index_has_a_commit_delta_contract(self) -> None:
        workflow = (
            Path(__file__).resolve().parents[1] / ".github" / "workflows" / "ci.yml"
        ).read_text(encoding="utf-8")
        self.assertIn("fetch-depth: 0", workflow)
        self.assertIn(
            "RKC_QUALITY_BASE: ${{ github.event.pull_request.base.sha || github.event.before }}",
            workflow,
        )
        self.assertIn("quality_base=$(git mktree </dev/null)", workflow)
        self.assertIn(
            'git rev-parse --verify "${quality_base}^{tree}"', workflow
        )
        self.assertIn('--base "$quality_base"', workflow)

    def run_git(self, *arguments: str) -> None:
        subprocess.run(["git", "-C", str(self.root), *arguments], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    def test_build_render_write_and_main_for_arbitrary_folder(self) -> None:
        self.write("src/main.go", "package src\nfunc Main() {}\n")
        self.write("src/main_test.go", "package src\nfunc TestMain() {}\n")
        self.write("src/types.go", "package src\ntype Record struct{}\n")
        self.write("tools/worker.py", '"""worker docs"""\nprint(1)\n')
        self.write("docs/guide.md", "`src/main.go` and worker.py are documented.\n")
        output = self.root / "quality"
        go_profile = self.write("profiles/go.out", "mode: set\nsrc/main.go:2.1,2.18 2 1\n")
        go_report = self.write(
            "profiles/go-summary.json",
            json.dumps(
                {
                    "go": {
                        "zero_statement_files": ["src/types.go"],
                        "current_platform_excluded_files": [],
                    }
                }
            ),
        )
        python_report = self.write(
            "profiles/python.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "tools/worker.py": {
                            "missing_lines": [],
                            "missing_branches": [],
                            "summary": {
                                "num_statements": 2,
                                "covered_lines": 2,
                                "num_branches": 0,
                                "covered_branches": 0,
                            },
                        }
                    },
                }
            ),
        )
        built = index.build_index(
            self.root,
            output=output,
            go_profile=go_profile,
            go_report=go_report,
            python_report=python_report,
        )
        self.assertFalse(any(record["path"].startswith("quality/") for record in built["files"]))
        self.assertEqual(built["project"], "RKC")
        self.assertEqual(built["publisher"], "NeuroForgeIO")
        self.assertEqual(built["license"]["spdx"], "Apache-2.0")
        self.assertEqual(built["summary"]["profiling_file_percent"], 100.0)
        self.assertEqual(built["summary"]["profile_uncovered_units"], 0)
        self.assertEqual(built["summary"]["profiling_zero_executable_files"], 1)
        self.assertEqual(built["summary"]["inventory_accounting_percent"], 100.0)
        self.assertEqual(
            built["summary"]["inventory_accounted_files"],
            built["summary"]["admitted_regular_files"],
        )
        self.assertEqual(
            next(record for record in built["files"] if record["path"] == "src/types.go")[
                "profile"
            ]["status"],
            "zero-executable",
        )
        self.assertTrue(any(record["is_test"] for record in built["files"]))
        self.assertEqual(
            next(record for record in built["files"] if record["path"] == "src/main.go")[
                "documentation"
            ]["status"],
            "evidence",
        )
        markdown = index.render_markdown(built)
        self.assertIn("RKC quality index", markdown)
        self.assertIn("Apache License, Version 2.0", markdown)
        self.assertIn("copyright 2026 **NeuroForgeIO**", markdown)
        self.assertIn("LICENSE and NOTICE terms", markdown)
        self.assertIn("`MANIFEST.json` is the deterministic publication receipt", markdown)
        self.assertIn("Production source files in evidence denominator", markdown)
        self.assertIn("Inventory accounting | 100.0%", markdown)
        json_path, markdown_path, receipt_path = index.write_index(built, output)
        self.assertTrue(json_path.is_file())
        self.assertTrue(markdown_path.is_file())
        self.assertTrue(receipt_path.is_file())
        self.assertEqual(
            json.loads(json_path.read_text(encoding="utf-8"))["schema_version"],
            "1.1.0",
        )
        self.assertEqual(index.main(["--root", str(self.root), "--output", str(output)]), 0)
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            self.assertEqual(index.main(["--root", str(self.root / "missing")]), 1)
            self.assertIn("failed closed", errors.getvalue())
        if hasattr(os, "symlink"):
            linked = self.root / "linked-output"
            linked.symlink_to(output, target_is_directory=True)
            with self.assertRaisesRegex(index.QualityIndexError, "real directory"):
                index.write_index(built, linked)
            parent_link = self.root / "parent-link"
            parent_link.symlink_to(self.root, target_is_directory=True)
            with self.assertRaisesRegex(index.QualityIndexError, "real directory ancestors"):
                index.write_index(built, parent_link / "nested-output")

    def test_quality_artifact_receipt_is_deterministic_and_non_circular(self) -> None:
        self.write(
            "tools/worker.py",
            '"""A documented worker."""\nprint("ready")\n',
        )
        self.write("tools/test_worker.py", "def test_worker():\n    pass\n")
        output = self.root / "quality"
        built = index.build_index(self.root, output=output)

        with self.assertRaisesRegex(index.QualityIndexError, "inventory"):
            index._quality_artifact_receipt(built, {"index.json": b"{}\n"})
        incomplete_provenance = dict(built)
        incomplete_provenance.pop("source")
        with self.assertRaisesRegex(index.QualityIndexError, "provenance"):
            index._quality_artifact_receipt(
                incomplete_provenance,
                {"index.json": b"{}\n", "index.md": b"# report\n"},
            )

        replacements: list[str] = []
        replace = os.replace

        def observe(
            source: str | os.PathLike[str], target: str | os.PathLike[str]
        ) -> None:
            replacements.append(Path(target).name)
            replace(source, target)

        with mock.patch.object(index.os, "replace", side_effect=observe):
            json_path, markdown_path, receipt_path = index.write_index(built, output)
        self.assertEqual(
            replacements,
            ["index.json", "index.md", index.QUALITY_RECEIPT_NAME],
        )

        receipt_bytes = receipt_path.read_bytes()
        receipt = json.loads(receipt_bytes)
        self.assertEqual(receipt["schema_version"], "1.0.0")
        self.assertEqual(receipt["artifact"], "rkc-quality-index")
        self.assertEqual(receipt["generated_by"], built["generated_by"])
        self.assertEqual(receipt["source"], built["source"])
        self.assertEqual(receipt["source"]["root"], ".")
        self.assertNotIn(str(self.root), receipt_bytes.decode("utf-8"))

        integrity = receipt["integrity"]
        self.assertEqual(integrity["algorithm"], "sha256")
        self.assertEqual(
            [member["path"] for member in integrity["files"]],
            ["index.json", "index.md"],
        )
        self.assertNotIn(
            index.QUALITY_RECEIPT_NAME,
            {member["path"] for member in integrity["files"]},
        )
        self.assertFalse(integrity["receipt_included_in_files"])
        for member in integrity["files"]:
            content = (output / member["path"]).read_bytes()
            self.assertEqual(member["size_bytes"], len(content))
            self.assertEqual(member["sha256"], hashlib.sha256(content).hexdigest())
        canonical_inventory = json.dumps(
            integrity["files"],
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        self.assertEqual(
            integrity["inventory_sha256"],
            hashlib.sha256(canonical_inventory).hexdigest(),
        )

        original_json = json_path.read_bytes()
        original_markdown = markdown_path.read_bytes()
        index.write_index(built, output)
        self.assertEqual(receipt_path.read_bytes(), receipt_bytes)
        self.assertEqual(json_path.read_bytes(), original_json)
        self.assertEqual(markdown_path.read_bytes(), original_markdown)

        staging = self.root / "failed-staging"
        staging.mkdir()
        with mock.patch.object(
            index.os, "fsync", side_effect=OSError("simulated sync failure")
        ):
            with self.assertRaisesRegex(OSError, "sync failure"):
                index._stage_output_member(staging, "index.json", b"{}\n")
        self.assertEqual(list(staging.iterdir()), [])
        with mock.patch.object(index.os, "O_DIRECTORY", None, create=True):
            index._fsync_output_directory(output)

    def test_receipt_remains_fail_closed_when_payload_publication_fails(self) -> None:
        self.write("worker.py", '"""Worker."""\nprint("before")\n')
        output = self.root / "quality"
        original = index.build_index(self.root, output=output)
        _, _, receipt_path = index.write_index(original, output)
        previous_receipt_bytes = receipt_path.read_bytes()
        previous_receipt = json.loads(previous_receipt_bytes)

        changed = json.loads(json.dumps(original))
        changed["summary"]["open_gaps"] += 1
        replace = os.replace

        def fail_second_member(
            source: str | os.PathLike[str], target: str | os.PathLike[str]
        ) -> None:
            if Path(target).name == "index.md":
                raise OSError("simulated publication interruption")
            replace(source, target)

        with mock.patch.object(index.os, "replace", side_effect=fail_second_member):
            with self.assertRaisesRegex(OSError, "publication interruption"):
                index.write_index(changed, output)

        self.assertEqual(receipt_path.read_bytes(), previous_receipt_bytes)
        recorded = {
            member["path"]: member for member in previous_receipt["integrity"]["files"]
        }
        self.assertNotEqual(
            hashlib.sha256((output / "index.json").read_bytes()).hexdigest(),
            recorded["index.json"]["sha256"],
        )
        self.assertFalse(
            [path.name for path in output.iterdir() if path.name.startswith(".")]
        )

    def test_complete_inventory_separates_quality_scope(self) -> None:
        self.write("pkg/main.go", "package pkg\nfunc Main() {}\n")
        self.write("pkg/main_test.go", "package pkg\nfunc TestMain() {}\n")
        self.write("docs/guide.md", "`pkg/main.go` is documented.\n")
        for relative in (
            "Makefile",
            ".github/workflows/ci.yml",
            "schema/config.json",
            "migrations/001.sql",
        ):
            self.write(relative)

        built = index.build_index(self.root)
        source = {record["path"] for record in built["files"]}
        documentation = {record["path"] for record in built["documentation"]}
        other = {record["path"] for record in built["other_files"]}
        self.assertFalse(source & documentation or source & other or documentation & other)
        self.assertEqual(
            source | documentation | other,
            {
                "pkg/main.go",
                "pkg/main_test.go",
                "docs/guide.md",
                "Makefile",
                ".github/workflows/ci.yml",
                "schema/config.json",
                "migrations/001.sql",
            },
        )
        self.assertEqual(built["summary"]["admitted_regular_files"], 7)
        self.assertEqual(built["summary"]["analyzable_source_files"], 2)
        self.assertEqual(built["summary"]["production_source_files"], 1)
        self.assertEqual(built["summary"]["test_source_files"], 1)
        self.assertEqual(built["summary"]["documentation_files"], 1)
        self.assertEqual(built["summary"]["other_regular_files"], 4)
        self.assertEqual(built["summary"]["inventory_accounting_percent"], 100.0)
        self.assertEqual(built["summary"]["test_evidence_percent"], 100.0)
        self.assertEqual(built["summary"]["documentation_evidence_percent"], 100.0)
        self.assertTrue(
            all(
                record["analysis"]["status"] == "not-applicable"
                and record["git_status"] == "unavailable"
                for record in built["other_files"]
            )
        )

    def test_build_index_rejects_a_concurrent_file_change(self) -> None:
        source = self.write("worker.py", "print('before')\n")

        def mutate(_path: Path) -> bool:
            source.write_text("print('after')\n", encoding="utf-8")
            return False

        with mock.patch.object(index, "_generated", side_effect=mutate):
            with self.assertRaisesRegex(index.QualityIndexError, "changed during indexing"):
                index.build_index(self.root)

    def test_main_can_fail_closed_when_strict_gap_mode_is_requested(self) -> None:
        self.write("src/main.go", "package src\nfunc Main() {}\n")
        output = self.root / "quality"
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            self.assertEqual(
                index.main(
                    [
                        "--root",
                        str(self.root),
                        "--output",
                        str(output),
                        "--fail-on-gaps",
                    ]
                ),
                1,
            )
            self.assertIn("evidence gap", errors.getvalue())
        self.assertTrue((output / "index.json").is_file())

    def test_partial_profiles_and_profile_errors_are_actionable(self) -> None:
        self.write("pkg/main.go", "// Package pkg is a profile fixture.\npackage pkg\nfunc Main() {}\n")
        self.write("pkg/main_test.go", "package pkg\nfunc TestMain() {}\n")
        self.write("docs/pkg.md", "pkg/main.go is covered by the fixture.\n")
        partial = self.write(
            "profiles/partial.out",
            "mode: set\n"
            "pkg/main.go:3.1,3.14 2 0\n",
        )
        report = index.build_index(self.root, go_profile=partial)
        profile_gaps = [gap for gap in report["gaps"] if gap["kind"] == "profiling"]
        self.assertEqual(len(profile_gaps), 1)
        self.assertIn("2 of 2", profile_gaps[0]["detail"])
        self.assertEqual(profile_gaps[0]["uncovered"]["regions"][0]["start_line"], 3)
        self.assertIn("L3:1-L3:14", index.render_markdown(report))

        malformed = self.write("profiles/malformed.out", "mode: set\nnot a profile row\n")
        output = self.root / "strict-quality"
        with mock.patch("sys.stderr", new=io.StringIO()) as errors:
            status = index.main(
                [
                    "--root",
                    str(self.root),
                    "--output",
                    str(output),
                    "--go-profile",
                    str(malformed),
                ]
            )
        self.assertEqual(status, 1)
        self.assertIn("profile error", errors.getvalue())
        payload = json.loads((output / "index.json").read_text(encoding="utf-8"))
        self.assertTrue(payload["profile_errors"])
        self.assertEqual(payload["summary"]["profile_errors"], 1)
        self.assertIn("Profile errors", (output / "index.md").read_text(encoding="utf-8"))

    def test_filesystem_observation_failures_are_explicit(self) -> None:
        source = self.write("source.py", "print('safe')\n")
        excluded = self.write("coverage.out", "ignored\n")
        del excluded

        with self.assertRaisesRegex(index.QualityIndexError, "escapes"):
            index._relative(self.root.parent / "outside.py", self.root)
        files, _ = index._walk_files(
            self.root, self.root.parent / "outside-quality"
        )
        self.assertEqual(files, [source])

        if hasattr(os, "mkfifo"):
            fifo = self.root / "events.pipe"
            os.mkfifo(fifo)
            _, exclusions = index._walk_files(self.root, None)
            self.assertIn(
                {"path": "events.pipe", "reason": "non-regular-file"},
                exclusions,
            )

        real_lstat = os.lstat
        bad_directory = self.root / "bad-directory"
        bad_directory.mkdir()

        def fail_directory(candidate: str | os.PathLike[str]) -> os.stat_result:
            if Path(candidate) == bad_directory:
                raise PermissionError("directory observation denied")
            return real_lstat(candidate)

        with mock.patch.object(index.os, "lstat", side_effect=fail_directory):
            with self.assertRaisesRegex(index.QualityIndexError, "cannot inspect"):
                index._walk_files(self.root, None)

        regular_info = real_lstat(source)

        def replace_directory_type(
            candidate: str | os.PathLike[str],
        ) -> os.stat_result:
            if Path(candidate) == bad_directory:
                return regular_info
            return real_lstat(candidate)

        with mock.patch.object(
            index.os, "lstat", side_effect=replace_directory_type
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "not a directory"):
                index._walk_files(self.root, None)

        denied_file = self.write("denied.txt", "private\n")

        def fail_file(candidate: str | os.PathLike[str]) -> os.stat_result:
            if Path(candidate) == denied_file:
                raise PermissionError("file observation denied")
            return real_lstat(candidate)

        with mock.patch.object(index.os, "lstat", side_effect=fail_file):
            with self.assertRaisesRegex(index.QualityIndexError, "cannot inspect"):
                index._walk_files(self.root, None)
        with mock.patch.object(
            index.os, "open", side_effect=PermissionError("read denied")
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "cannot read"):
                index._file_stats_with_identity(source, self.root)

        stable = (1, 2, 3, 4, stat.S_IFREG)
        changed = (1, 2, 3, 5, stat.S_IFREG)
        with mock.patch.object(
            index,
            "_stat_identity",
            side_effect=[stable, stable, stable, changed],
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "changed while"):
                index._file_stats_with_identity(source, self.root)

    def test_profile_parsers_reject_remaining_ambiguous_evidence(self) -> None:
        source_paths = {"pkg/api.go"}
        go_profile = self.write(
            "remaining-go.out",
            "mode: set\n"
            "\n"
            "pkg/api.go:1.1,1.2 1 0\n"
            "pkg/api.go:1.1,1.2 2 1\n"
            "pkg/api.go:1.1,1.2 1 1\n"
            "pkg/api.go:2.1,2.2 0 0\n",
        )
        values, errors = index._go_profile(go_profile, source_paths, self.root)
        self.assertEqual(len(errors), 1)
        self.assertEqual(values["pkg/api.go"]["statements"], 0)
        self.assertEqual(values["pkg/api.go"]["uncovered_regions"], [])

        python_sources = {
            "missing-summary.py",
            "bad-counter.py",
            "bad-lines.py",
            "bad-branches.py",
            "branch-count.py",
            "duplicate.py",
        }

        def summary(
            statements: int = 0,
            covered: int = 0,
            branches: int = 0,
            covered_branches: int = 0,
        ) -> dict[str, int]:
            return {
                "num_statements": statements,
                "covered_lines": covered,
                "num_branches": branches,
                "covered_branches": covered_branches,
            }

        python_report = self.write(
            "remaining-python.json",
            json.dumps(
                {
                    "meta": {"branch_coverage": True},
                    "files": {
                        "missing-summary.py": {"summary": []},
                        "bad-counter.py": {
                            "summary": {
                                **summary(),
                                "num_statements": True,
                            },
                            "missing_lines": [],
                            "missing_branches": [],
                        },
                        "bad-lines.py": {
                            "summary": summary(1, 0),
                            "missing_lines": "not-a-list",
                            "missing_branches": [],
                        },
                        "bad-branches.py": {
                            "summary": summary(branches=1),
                            "missing_lines": [],
                            "missing_branches": "not-a-list",
                        },
                        "branch-count.py": {
                            "summary": summary(branches=2),
                            "missing_lines": [],
                            "missing_branches": [[1, -1]],
                        },
                        "duplicate.py": {
                            "summary": summary(),
                            "missing_lines": [],
                            "missing_branches": [],
                        },
                        str(self.root / "duplicate.py"): {
                            "summary": summary(),
                            "missing_lines": [],
                            "missing_branches": [],
                        },
                    },
                }
            ),
        )
        values, errors = index._python_profile(
            python_report, python_sources, self.root
        )
        self.assertEqual(set(values), {"duplicate.py"})
        self.assertEqual(len(errors), 6)
        self.assertTrue(any("no summary" in error for error in errors))
        self.assertTrue(any("invalid num_statements" in error for error in errors))
        self.assertTrue(any("invalid missing_lines" in error for error in errors))
        self.assertTrue(any("invalid missing_branches" in error for error in errors))
        self.assertTrue(any("missing-branch" in error for error in errors))
        self.assertTrue(any("repeats" in error for error in errors))

        missing_metadata = index._go_profile_metadata(
            self.root / "missing-metadata.json", source_paths, self.root
        )
        self.assertIn("cannot read", missing_metadata[2][0])
        non_object = self.write("metadata-array.json", "[]")
        self.assertIn(
            "not an object",
            index._go_profile_metadata(non_object, source_paths, self.root)[2][0],
        )
        no_report = self.write("metadata-no-report.json", '{"go": []}')
        self.assertIn(
            "no report object",
            index._go_profile_metadata(no_report, source_paths, self.root)[2][0],
        )
        invalid_paths = self.write(
            "metadata-paths.json",
            json.dumps(
                {
                    "zero_statement_files": [7, "unknown.go"],
                    "current_platform_excluded_files": ["pkg/api.go"],
                }
            ),
        )
        zero, excluded, metadata_errors = index._go_profile_metadata(
            invalid_paths, source_paths, self.root
        )
        self.assertEqual(zero, set())
        self.assertEqual(excluded, {"pkg/api.go"})
        self.assertEqual(len(metadata_errors), 2)
        self.assertEqual(
            index._profile_result(
                "go", "pkg/api.go", {}, {}, True, False, set(), excluded
            )["status"],
            "platform-excluded",
        )
        self.assertIsNone(
            index._resolve_profile_path(
                str(self.root.parent / "outside.go"), source_paths, self.root
            )
        )

    def test_git_and_build_provenance_fail_closed_at_final_observation(self) -> None:
        with mock.patch.object(
            index.subprocess, "run", side_effect=OSError("git unavailable")
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "Git inspection"):
                index._run_git(self.root, ["status"])

        failed = subprocess.CompletedProcess([], 1, stdout="", stderr="")
        available = {"status": "available", "commit": "a" * 40, "tree": "b" * 40}
        with mock.patch.object(index, "_run_git", return_value=failed):
            self.assertEqual(
                index._git_tracked_paths(self.root, available)["status"],
                "unavailable",
            )
            self.assertEqual(
                index._git_stability_token(self.root, available)["status"],
                "unavailable",
            )
        with self.assertRaisesRegex(index.QualityIndexError, "incomplete"):
            index._parse_git_changes("M\0")

        successful_diff = subprocess.CompletedProcess(
            [], 0, stdout="M\0tracked.py\0", stderr=""
        )
        with mock.patch.object(
            index, "_run_git", side_effect=[successful_diff, failed]
        ):
            delta = index._git_changes(self.root, None, available)
        self.assertEqual(delta["items"], [{"status": "M", "path": "tracked.py"}])

        self.write("worker.py", '"""Documented worker."""\nprint("ok")\n')
        first = {"status": "unavailable", "reason": "first observation"}
        second = {"status": "unavailable", "reason": "changed observation"}
        with mock.patch.object(index, "_git_identity", side_effect=[first, second]):
            with self.assertRaisesRegex(index.QualityIndexError, "Git commit"):
                index.build_index(self.root)

        real_walk = index._walk_files
        walk_count = 0

        def change_inventory(
            root: Path, output: Path | None
        ) -> tuple[list[Path], list[dict[str, str]]]:
            nonlocal walk_count
            walk_count += 1
            files, exclusions = real_walk(root, output)
            if walk_count == 2:
                exclusions = [*exclusions, {"path": "late", "reason": "changed"}]
            return files, exclusions

        with mock.patch.object(index, "_walk_files", side_effect=change_inventory):
            with self.assertRaisesRegex(index.QualityIndexError, "inventory changed"):
                index.build_index(self.root)

        real_lstat = os.lstat
        observed = 0

        def remove_before_revalidation(
            candidate: str | os.PathLike[str],
        ) -> os.stat_result:
            nonlocal observed
            if Path(candidate) == self.root / "worker.py":
                observed += 1
                if observed == 4:
                    raise FileNotFoundError("removed after indexing")
            return real_lstat(candidate)

        with mock.patch.object(
            index.os, "lstat", side_effect=remove_before_revalidation
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "cannot revalidate"):
                index.build_index(self.root)

        overlap = self.root / "overlap"
        overlap.mkdir()
        (overlap / "guide.md").write_text("plain words\n", encoding="utf-8")
        with mock.patch.object(index, "_language", return_value="python"):
            with self.assertRaisesRegex(index.QualityIndexError, "categories overlap"):
                index.build_index(overlap)

    def test_render_and_publication_boundary_variants(self) -> None:
        self.write("worker.py", '"""Documented worker."""\nprint("ok")\n')
        report = index.build_index(self.root)
        report["gaps"] = []
        report["deltas"] = {
            "status": "available",
            "scope": "working-tree",
            "items": [{"status": "M", "path": "worker.py"}],
        }
        rendered = index.render_markdown(report)
        self.assertIn("No gaps were detected", rendered)
        self.assertIn("`M` `worker.py`", rendered)

        regions: list[object] = ["invalid"]
        regions.extend(
            {
                "start_line": number,
                "start_column": 1,
                "end_line": number,
                "end_column": 2,
                "units": 1,
            }
            for number in range(1, 10)
        )
        region_hint = index._uncovered_hint({"regions": regions})
        self.assertIn("+2 more", region_hint)
        location_hint = index._uncovered_hint(
            {
                "lines": list(range(1, 11)),
                "branches": ["invalid", *[[line, -1] for line in range(1, 10)]],
            }
        )
        self.assertIn("+2 more", location_hint)
        self.assertIn("branches ", location_hint)
        self.assertEqual(index._uncovered_hint({}), "")

        impossible = Path("/") / "rkc-quality-parent-does-not-exist"
        with mock.patch.object(index.os, "lstat", side_effect=FileNotFoundError):
            with self.assertRaisesRegex(index.QualityIndexError, "parent does not exist"):
                index._safe_output_directory(impossible)

        replaced = self.root / "replaced" / "quality"
        regular_info = os.lstat(self.root / "worker.py")
        real_lstat = os.lstat

        def replace_created_directory(
            candidate: str | os.PathLike[str],
        ) -> os.stat_result:
            path = Path(candidate)
            if path == replaced and path.exists():
                return regular_info
            return real_lstat(candidate)

        with mock.patch.object(
            index.os, "lstat", side_effect=replace_created_directory
        ):
            with self.assertRaisesRegex(index.QualityIndexError, "replaced unsafely"):
                index._safe_output_directory(replaced)

        staging = self.root / "short-write"
        staging.mkdir()

        class ShortWriter:
            def __init__(self, descriptor: int) -> None:
                self.descriptor = descriptor

            def __enter__(self) -> ShortWriter:
                return self

            def __exit__(self, *_arguments: object) -> None:
                os.close(self.descriptor)

            def write(self, content: bytes) -> int:
                return max(0, len(content) - 1)

            def flush(self) -> None:
                return None

            def fileno(self) -> int:
                return self.descriptor

        with mock.patch.object(
            index.os, "fdopen", side_effect=lambda descriptor, _mode: ShortWriter(descriptor)
        ):
            with self.assertRaisesRegex(OSError, "short write"):
                index._stage_output_member(staging, "index.json", b"{}\n")
        self.assertEqual(list(staging.iterdir()), [])

        script = Path(index.__file__).resolve()
        with mock.patch.object(
            sys, "argv", [str(script), "--root", str(self.root / "absent")]
        ), mock.patch("sys.stderr", new=io.StringIO()):
            with self.assertRaisesRegex(SystemExit, "1"):
                runpy.run_path(str(script), run_name="__main__")

    def test_remaining_association_and_cleanup_boundaries(self) -> None:
        self.write("main.rs", "fn main() {}\n")
        rust_report = index.build_index(self.root)
        self.assertEqual(rust_report["files"][0]["language"], "rust")
        self.assertFalse(index._text_mentions_path("no source reference", "x.py"))

        go_evidence = index._test_evidence(
            "pkg/service.go",
            "go",
            ["pkg/service.go", "pkg/service_test.go"],
            {"pkg/service_test.go": "package pkg\nfunc TestRun() {}\n"},
            "service",
        )
        self.assertEqual(go_evidence, ["pkg/service_test.go"])

        generated = self.write(
            "pkg/generated.go",
            "// Code generated by fixture. DO NOT EDIT.\npackage pkg\n",
        )
        source = self.write("pkg/source.go", "package pkg\n")
        package_docs = index._go_package_documentation(
            self.root, ["pkg/generated.go", "pkg/source.go"]
        )
        self.assertEqual(package_docs, {})
        del generated
        documentation = index._documentation_evidence(
            "pkg/source.go", source, {}, self.root
        )
        self.assertEqual(documentation["status"], "gap")

        short_hint = index._uncovered_hint(
            {"lines": [7], "branches": [[7, -1]]}
        )
        self.assertEqual(short_hint, "lines 7; branches 7->-1")

        vanished = self.root / "vanished-stage"
        vanished.mkdir()
        staged_path: list[Path] = []
        real_mkstemp = tempfile.mkstemp

        def remember_stage(*arguments: object, **keywords: object) -> tuple[int, str]:
            descriptor, raw = real_mkstemp(*arguments, **keywords)
            staged_path.append(Path(raw))
            return descriptor, raw

        class VanishingWriter:
            def __init__(self, descriptor: int) -> None:
                self.descriptor = descriptor

            def __enter__(self) -> VanishingWriter:
                return self

            def __exit__(self, *_arguments: object) -> None:
                os.close(self.descriptor)

            def write(self, _content: bytes) -> int:
                staged_path[-1].unlink()
                raise OSError("staged member disappeared")

        with mock.patch.object(
            index.tempfile, "mkstemp", side_effect=remember_stage
        ), mock.patch.object(
            index.os,
            "fdopen",
            side_effect=lambda descriptor, _mode: VanishingWriter(descriptor),
        ):
            with self.assertRaisesRegex(OSError, "disappeared"):
                index._stage_output_member(vanished, "index.json", b"{}\n")
        self.assertEqual(list(vanished.iterdir()), [])

        output = self.root / "cleanup-publication"
        output.mkdir()
        missing_stages = [
            output / ".missing-index",
            output / ".missing-markdown",
            output / ".missing-manifest",
        ]
        with mock.patch.object(
            index, "_stage_output_member", side_effect=missing_stages
        ), mock.patch.object(
            index.os, "replace", side_effect=OSError("publication target changed")
        ):
            with self.assertRaisesRegex(OSError, "target changed"):
                index.write_index(rust_report, output)


if __name__ == "__main__":
    unittest.main()
